# Generated by Django 4.2.13 on 2026-08-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportlog',
            name='data_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='exportlog',
            name='export_type',
            field=models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'Excel'), ('PDF', 'PDF')], max_length=5),
        ),
    ]
