# Generated by Django 4.2.13 on 2026-08-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0002_exportlog_data_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportlog',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exportlog',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='exportlog',
            name='sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
