# Generated by Django 5.0.6 on 2026-06-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('NCA_ADMIN', 'System Administrator'), ('NCA_OFFICER', 'NCA Officer'), ('PROVIDER_DATA_ENTRY', 'Provider Data Entry User'), ('PROVIDER_APPROVER', 'Provider Approver')], max_length=30),
        ),
    ]
