# Generated by Django 4.2.13 on 2026-08-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_provider_admin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('NCA_ADMIN', 'System Administrator'), ('NCA_OFFICER', 'NCA Officer'), ('NCA_VIEWER', 'NCA Data Requester'), ('PROVIDER_DATA_ENTRY', 'Provider Data Entry User'), ('PROVIDER_APPROVER', 'Provider Approver')], max_length=30),
        ),
    ]
