# Generated by Django 5.0.6 on 2026-06-08 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('registered_name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('MNO', 'MNO'), ('ISP', 'ISP'), ('PAY_TV', 'Pay TV'), ('TOWER_OPERATOR', 'Tower Operator'), ('TOWER_MAIN', 'Tower Main'), ('DOMESTIC_FIBRE', 'Domestic Fibre'), ('SUBMARINE_FIBRE', 'Submarine Fibre')], max_length=30)),
                ('licence_type', models.CharField(max_length=100)),
                ('licence_number', models.CharField(max_length=100)),
                ('licence_issue_date', models.DateField(blank=True, null=True)),
                ('licence_expiry_date', models.DateField(blank=True, null=True)),
                ('physical_address', models.TextField(blank=True)),
                ('digital_address', models.CharField(blank=True, max_length=20)),
                ('postal_address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('primary_email', models.EmailField(max_length=254)),
                ('primary_phone', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_profile', to='users.organization')),
            ],
            options={
                'ordering': ['registered_name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('notification_role', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_on_period_open', models.BooleanField(default=True)),
                ('notify_on_reminder', models.BooleanField(default=True)),
                ('notify_on_review', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='providers.providerprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
