# Generated by Django 4.2.13 on 2026-08-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='sector',
            field=models.CharField(choices=[('TELECOM', 'Telecom'), ('BROADCASTING', 'Broadcasting')], default='TELECOM', max_length=20),
        ),
    ]
