# Generated by Django 4.2.13 on 2026-08-05 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('FULL', 'Full'), ('DIFFERENTIAL', 'Differential'), ('WAL', 'WAL archive'), ('FILES', 'Private files')], max_length=20)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('VERIFIED', 'Verified')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('storage_reference', models.CharField(max_length=500)),
                ('manifest_sha256', models.CharField(blank=True, max_length=64)),
                ('encrypted', models.BooleanField(default=False)),
                ('immutable_copy', models.BooleanField(default=False)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('details', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='OperationalTaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=150)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='RestoreDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drill_type', models.CharField(choices=[('AUTOMATED', 'Automated verification'), ('FULL', 'Full recovery exercise')], max_length=20)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('measured_rpo_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('measured_rto_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('checks', models.JSONField(default=dict)),
                ('evidence_reference', models.CharField(blank=True, max_length=500)),
                ('signed_off_at', models.DateTimeField(blank=True, null=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restore_drills', to='governance.backuprun')),
                ('signed_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecordRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_class', models.CharField(choices=[('FORM_VERSION', 'Form versions'), ('SUBMISSION', 'Submissions'), ('AUDIT', 'Audit records'), ('PRIVATE_UPLOAD', 'Private uploads'), ('RECEIPT', 'Submission receipts'), ('EXPORT', 'Exports'), ('EMAIL', 'Email records'), ('DATA_REQUEST', 'Data requests'), ('SUPPORT', 'Support tickets')], max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('retention_days', models.PositiveIntegerField(blank=True, null=True)),
                ('trigger_field', models.CharField(default='created_at', max_length=100)),
                ('rationale', models.TextField(blank=True)),
                ('authority_reference', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retention_policies_approved', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retention_policies_prepared', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LegalHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('record_class', models.CharField(blank=True, choices=[('FORM_VERSION', 'Form versions'), ('SUBMISSION', 'Submissions'), ('AUDIT', 'Audit records'), ('PRIVATE_UPLOAD', 'Private uploads'), ('RECEIPT', 'Submission receipts'), ('EXPORT', 'Exports'), ('EMAIL', 'Email records'), ('DATA_REQUEST', 'Data requests'), ('SUPPORT', 'Support tickets')], max_length=30)),
                ('provider_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reporting_period_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('submission_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('target_ids', models.JSONField(default=list)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('authority_reference', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Released')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_holds_created', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legal_holds_released', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DispositionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dry_run', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PREVIEWED', 'Previewed'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('held_count', models.PositiveIntegerField(default=0)),
                ('disposed_count', models.PositiveIntegerField(default=0)),
                ('certificate_sha256', models.CharField(blank=True, max_length=64)),
                ('details', models.JSONField(default=dict)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disposition_runs_approved', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposition_runs', to='governance.recordretentionpolicy')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposition_runs_requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='recordretentionpolicy',
            constraint=models.UniqueConstraint(fields=('record_class', 'version'), name='unique_retention_policy_version'),
        ),
    ]
