# Generated by Django 4.2.13 on 2026-08-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalhold',
            name='target_date_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalhold',
            name='target_date_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
