"use client";

import { useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, BookOpenText, CheckCircle2, Download, FileSearch, Loader2, Search } from "lucide-react";
import { api, ApiError, downloadAuthenticated } from "@/lib/api";

type ReportType = "QUARTERLY_BULLETIN" | "CIR";
type Template = { id:number; report_type:ReportType; name:string; version:number; effective_year:number; effective_quarter:number|null; filename_pattern:string; source_reference:string; status:string; latest_period:string|null };
type Change = { key:string; section:string; location:string; field:string; template_value:string; new_value:string; source_period:string; target_period:string; data_source:string; mapping_status:string };
type Preparation = { id:string; report_type:ReportType; year:number; quarter:number|null; status:"READY"|"MISSING_DATA"|"MAPPING_REQUIRED"|"CALCULATION_ERROR"|"STALE"; template_name:string; template_version:number; created_at:string; expires_at:string; manifest:{ context:{period_label:string}; template:{source_reference:string}; changes:Change[]; missing:string[]; mapping_required:string[]; sources:{submission_id:number;reference:string;revision:number}[] } };
type Artifact = { id:string; report_type:ReportType; year:number; quarter:number|null; template_version:number; status:"PREPARING"|"READY"|"FAILED"; filename:string; file_size:number; sha256:string; error_message:string; generated_by_name:string; created_at:string; completed_at:string|null };

const reportLabels:Record<ReportType,string>={QUARTERLY_BULLETIN:"Quarterly Statistical Bulletin",CIR:"Annual Communications Industry Report"};
const statusLabels:Record<Preparation["status"],string>={READY:"Ready to generate",MISSING_DATA:"More approved information is needed",MAPPING_REQUIRED:"More report information is needed",CALCULATION_ERROR:"Some figures could not be calculated",STALE:"Report information has changed"};

function bytes(value:number){if(value<1024)return `${value} B`;if(value<1048576)return `${(value/1024).toFixed(1)} KB`;return `${(value/1048576).toFixed(1)} MB`}
function periodLabel(type:ReportType,year:number,quarter:number|null){return type==="CIR"?String(year):`Q${quarter} ${year}`}

export default function ReportsPage(){
 const qc=useQueryClient();
 const {data:definitionData,isLoading:loadingDefinitions}=useQuery<{results:Template[]}>({queryKey:["report-definitions"],queryFn:()=>api("/reports/definitions/")});
 const {data:periodData}=useQuery<{years:number[];quarters:number[]}>({queryKey:["report-periods"],queryFn:()=>api("/reports/periods/")});
 const {data:historyData,isLoading:loadingHistory}=useQuery<{results:Artifact[]}>({queryKey:["report-history"],queryFn:()=>api("/reports/history/")});
 const templates=definitionData?.results??[]; const years=periodData?.years?.length?periodData.years:[new Date().getFullYear()];
 const [selectedType,setSelectedType]=useState<ReportType>("QUARTERLY_BULLETIN"); const [year,setYear]=useState<number>(years[0]??new Date().getFullYear()); const [quarter,setQuarter]=useState(1);
 const [preparation,setPreparation]=useState<Preparation|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [query,setQuery]=useState(""); const [notice,setNotice]=useState("");
 const selectedTemplate=templates.find(item=>item.report_type===selectedType);
 const visibleChanges=useMemo(()=>{const needle=query.trim().toLowerCase();return preparation?.manifest.changes.filter(item=>!needle||[item.section,item.field,item.location,item.data_source,item.new_value].some(value=>value.toLowerCase().includes(needle)))??[]},[preparation,query]);
 async function prepare(){setBusy(true);setError("");setNotice("");try{const result=await api.post<Preparation>("/reports/prepare/",{report_type:selectedType,year,quarter:selectedType==="QUARTERLY_BULLETIN"?quarter:null});setPreparation(result)}catch(e){setError(e instanceof ApiError?e.message:"The report could not be prepared.")}finally{setBusy(false)}}
 async function generate(){if(!preparation)return;setBusy(true);setError("");try{const result=await api.post<Artifact>(`/reports/preparations/${preparation.id}/generate/`,{idempotency_key:crypto.randomUUID()});await qc.invalidateQueries({queryKey:["report-history"]});setNotice(`${result.filename} was generated successfully.`)}catch(e){setError(e instanceof ApiError?e.message:"The report could not be generated.")}finally{setBusy(false)}}
 function choose(type:ReportType){setSelectedType(type);setPreparation(null);setError("");setNotice("")}
 return <main className="mx-auto max-w-7xl space-y-7">
  <header><p className="text-sm font-semibold uppercase tracking-wide text-[#0066cc]">Publications</p><h1 className="mt-1 text-3xl font-semibold text-[#17191c]">Reports</h1><p className="mt-2 max-w-3xl text-sm text-[#737780]">Generate quarterly bulletins and annual industry reports using approved regulatory information.</p></header>
  <section className="grid gap-4 md:grid-cols-2">{loadingDefinitions?<div className="col-span-2 rounded-2xl border bg-white p-8 text-sm text-[#737780]">Loading reports…</div>:templates.map(item=><button key={item.id} onClick={()=>choose(item.report_type)} className={`rounded-2xl border bg-white p-6 text-left transition ${selectedType===item.report_type?"border-[#0066cc] ring-2 ring-[#0066cc]/10":"border-[#e1e4e8] hover:border-[#9fbad5]"}`}><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#eaf3fc] text-[#0066cc]"><BookOpenText size={22}/></span><h2 className="mt-5 text-xl font-semibold">{reportLabels[item.report_type]}</h2><p className="mt-2 text-sm text-[#737780]">{item.report_type==="CIR"?"Generate the annual report for a selected year.":"Generate a statistical bulletin for a selected quarter."}</p></button>)}</section>
  <section className="rounded-2xl border border-[#e1e4e8] bg-white p-6 md:p-8"><div><h2 className="text-xl font-semibold">{selectedType==="CIR"?"Generate Annual CIR":"Generate Quarterly Bulletin"}</h2><p className="mt-1 text-sm text-[#737780]">Choose the reporting period and review whether the required information is available.</p></div>
   <div className={`mt-6 grid gap-4 ${selectedType==="QUARTERLY_BULLETIN"?"sm:grid-cols-[180px_180px_auto]":"sm:grid-cols-[180px_auto]"}`}><label className="text-sm font-medium">Year<select value={year} onChange={e=>{setYear(Number(e.target.value));setPreparation(null)}} className="mt-1.5 w-full rounded-xl border border-[#c9cdd3] bg-white px-3 py-2.5">{years.map(value=><option key={value}>{value}</option>)}</select></label>{selectedType==="QUARTERLY_BULLETIN"&&<label className="text-sm font-medium">Quarter<select value={quarter} onChange={e=>{setQuarter(Number(e.target.value));setPreparation(null)}} className="mt-1.5 w-full rounded-xl border border-[#c9cdd3] bg-white px-3 py-2.5">{[1,2,3,4].map(value=><option key={value} value={value}>Quarter {value}</option>)}</select></label>}<button disabled={busy||!selectedTemplate} onClick={prepare} className="self-end justify-self-start rounded-xl bg-[#001f44] px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy?<span className="flex items-center gap-2"><Loader2 size={16} className="animate-spin"/>Checking</span>:"Check report data"}</button></div>
   {error&&<p className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{notice&&<p className="mt-5 rounded-xl bg-green-50 p-4 text-sm text-green-800">{notice}</p>}
   {preparation&&<div className="mt-8 space-y-6 border-t pt-7"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3">{preparation.status==="READY"?<CheckCircle2 className="text-green-600"/>:<AlertTriangle className="text-amber-600"/>}<div><h3 className="font-semibold">{statusLabels[preparation.status]}</h3><p className="text-sm text-[#737780]">{periodLabel(preparation.report_type,preparation.year,preparation.quarter)} · {preparation.manifest.sources.length} approved source submission(s) · {preparation.manifest.changes.length} registered change(s)</p></div></div><button disabled={busy||preparation.status!=="READY"} onClick={generate} className="rounded-xl bg-[#0066cc] px-5 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:bg-[#a8b7c7]">Generate PDF</button></div>
    {(preparation.manifest.mapping_required.length>0||preparation.manifest.missing.length>0)&&<div className="grid gap-4 lg:grid-cols-2">{preparation.manifest.mapping_required.length>0&&<ReadinessList title="Report information needed" items={preparation.manifest.mapping_required}/>} {preparation.manifest.missing.length>0&&<ReadinessList title="Approved information needed" items={preparation.manifest.missing}/>}</div>}
    <div><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">Report figures</h3><label className="relative"><Search size={15} className="absolute left-3 top-2.5 text-[#737780]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search figures" className="rounded-xl border py-2 pl-9 pr-3 text-sm"/></label></div><div className="mt-3 overflow-x-auto rounded-xl border"><table className="w-full min-w-[560px] text-left text-sm"><thead className="bg-[#f5f7f9] text-xs uppercase text-[#636a73]"><tr><th className="px-4 py-3">Section</th><th className="px-4 py-3">Indicator</th><th className="px-4 py-3">Value</th></tr></thead><tbody>{visibleChanges.map((item,index)=><tr key={`${item.key}-${index}`} className="border-t"><td className="px-4 py-3">{item.section||"—"}</td><td className="px-4 py-3 font-medium">{item.field}</td><td className="px-4 py-3">{item.new_value}</td></tr>)}</tbody></table>{visibleChanges.length===0&&<p className="p-6 text-center text-sm text-[#737780]">No figures match this search.</p>}</div></div>
   </div>}
  </section>
  <section className="rounded-2xl border border-[#e1e4e8] bg-white p-6 md:p-8"><div className="flex items-center gap-3"><FileSearch className="text-[#0066cc]"/><div><h2 className="text-xl font-semibold">Generated reports</h2><p className="text-sm text-[#737780]">Previously generated reports are listed newest first.</p></div></div><div className="mt-5 overflow-x-auto rounded-xl border"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#f5f7f9] text-xs uppercase text-[#636a73]"><tr><th className="px-4 py-3">Report</th><th className="px-4 py-3">Period</th><th className="px-4 py-3">Generated</th><th className="px-4 py-3">By</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">File</th></tr></thead><tbody>{(historyData?.results??[]).map(item=><tr key={item.id} className="border-t"><td className="px-4 py-3 font-medium">{reportLabels[item.report_type]}</td><td className="px-4 py-3">{periodLabel(item.report_type,item.year,item.quarter)}</td><td className="px-4 py-3">{new Date(item.created_at).toLocaleString()}</td><td className="px-4 py-3">{item.generated_by_name}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${item.status==="READY"?"bg-green-100 text-green-800":item.status==="FAILED"?"bg-red-100 text-red-800":"bg-blue-100 text-blue-800"}`}>{item.status.toLowerCase()}</span></td><td className="px-4 py-3">{item.status==="READY"?<button onClick={()=>downloadAuthenticated(`/reports/history/${item.id}/download/`,{},item.filename)} className="flex items-center gap-2 font-semibold text-[#0066cc]"><Download size={15}/>{item.filename} · {bytes(item.file_size)}</button>:item.error_message||"—"}</td></tr>)}</tbody></table>{loadingHistory&&<p className="p-6 text-sm text-[#737780]">Loading reports…</p>}{!loadingHistory&&!historyData?.results.length&&<p className="p-6 text-center text-sm text-[#737780]">No reports have been generated yet.</p>}</div></section>
 </main>
}

function ReadinessList({title,items}:{title:string;items:string[]}){return <div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><h4 className="font-semibold text-amber-950">{title} ({items.length})</h4><ul className="mt-3 max-h-52 space-y-2 overflow-auto text-sm text-amber-900">{items.map((item,index)=><li key={`${item}-${index}`} className="flex gap-2"><span>•</span><span>{item}</span></li>)}</ul></div>}
