# Generated by Django 4.2.13 on 2026-08-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_date', models.DateField(unique=True)),
                ('first_event_id', models.PositiveBigIntegerField(null=True)),
                ('last_event_id', models.PositiveBigIntegerField(null=True)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('root_hash', models.CharField(max_length=64)),
                ('signature', models.CharField(max_length=128)),
                ('exported_reference', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='auditevent',
            name='event_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
