# Generated by Django 4.2.13 on 2026-08-05 14:35

from django.db import migrations, models
import django.utils.timezone
import hashlib
import json


def backfill_hash_chain(apps, schema_editor):
    AuditEvent = apps.get_model("audit", "AuditEvent")
    previous = ""
    for event in AuditEvent.objects.order_by("id").iterator():
        payload = {
            "user_email": event.user_email,
            "role": event.role,
            "organization": event.organization,
            "action": event.action,
            "entity_type": event.entity_type,
            "entity_id": str(event.entity_id),
            "before": event.before_value,
            "after": event.after_value,
            "ip_address": str(event.ip_address or ""),
            "previous_hash": previous,
            "timestamp": event.timestamp.isoformat(),
        }
        canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str)
        event_hash = hashlib.sha256(canonical.encode("utf-8")).hexdigest()
        AuditEvent.objects.filter(pk=event.pk).update(previous_hash=previous, event_hash=event_hash)
        previous = event_hash


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditanchor_auditevent_event_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.RunPython(backfill_hash_chain, migrations.RunPython.noop),
    ]
