# Generated by Django 5.0.6 on 2026-06-03 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms_engine', '0001_initial'),
        ('submissions', '0002_initial'),
        ('uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionexcelbackup',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excel_backups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissionkmzupload',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to='forms_engine.kmzuploadrequirement'),
        ),
        migrations.AddField(
            model_name='submissionkmzupload',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kmz_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissionkmzupload',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kmz_uploads', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='submissionkmzupload',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kmz_uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
