# Generated by Django 4.2.13 on 2026-08-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionexcelbackup',
            name='scan_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submissionexcelbackup',
            name='scan_engine',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='submissionexcelbackup',
            name='scan_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CLEAN', 'Clean'), ('INFECTED', 'Infected'), ('ERROR', 'Scan error')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='submissionexcelbackup',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissionexcelbackup',
            name='sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='submissionkmzupload',
            name='scan_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submissionkmzupload',
            name='scan_engine',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='submissionkmzupload',
            name='scan_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CLEAN', 'Clean'), ('INFECTED', 'Infected'), ('ERROR', 'Scan error')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='submissionkmzupload',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissionkmzupload',
            name='sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
