# Generated by Django 5.2.16 on 2026-09-01 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0023_alter_formfield_field_type_and_more'),
        ('providers', '0004_providerprofile_provider_code'),
        ('submissions', '0011_expected_original_workflow_status'),
        ('uploads', '0004_submissionfieldattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelImportMappingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_fingerprint', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('mappings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excel_import_profiles_created', to=settings.AUTH_USER_MODEL)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_import_profiles', to='forms_engine.formtemplate')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_import_profiles', to='providers.providerprofile')),
            ],
            options={
                'ordering': ['-version', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionExcelImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SCANNING', 'Scanning'), ('PARSING', 'Parsing'), ('READY', 'Ready for review'), ('IMPORTING', 'Importing'), ('IMPORTED', 'Imported'), ('FAILED', 'Failed')], default='SCANNING', max_length=20)),
                ('parser_version', models.CharField(default='submission-xlsx-v1', max_length=80)),
                ('matcher_version', models.CharField(default='deterministic-v1', max_length=80)),
                ('layout_fingerprint', models.CharField(blank=True, max_length=64)),
                ('source_revision', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(default=dict)),
                ('errors', models.JSONField(default=list)),
                ('imported_manifest', models.JSONField(default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('resulting_revision', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='excel_import', to='uploads.submissionexcelbackup')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='excel_imports_confirmed', to=settings.AUTH_USER_MODEL)),
                ('mapping_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='uploads.excelimportmappingprofile')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_imports', to='submissions.submission')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excel_imports_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionExcelImportMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_locator', models.CharField(max_length=500)),
                ('source_sheet', models.CharField(max_length=255)),
                ('source_row', models.PositiveIntegerField()),
                ('source_column', models.CharField(blank=True, max_length=20)),
                ('indicator_code', models.CharField(blank=True, max_length=255)),
                ('indicator_name', models.CharField(max_length=500)),
                ('definition', models.TextField(blank=True)),
                ('source_data_type', models.CharField(blank=True, max_length=100)),
                ('raw_value', models.JSONField(blank=True, null=True)),
                ('converted_value', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('UNMATCHED', 'Unmatched'), ('AMBIGUOUS', 'Ambiguous'), ('DUPLICATE', 'Duplicate'), ('INVALID', 'Invalid'), ('SKIPPED', 'Skipped')], max_length=20)),
                ('score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('evidence', models.JSONField(default=dict)),
                ('target_type', models.CharField(blank=True, max_length=20)),
                ('target_key', models.CharField(blank=True, max_length=500)),
                ('grid_row_id', models.CharField(blank=True, max_length=100)),
                ('current_value', models.TextField(blank=True)),
                ('will_overwrite', models.BooleanField(default=False)),
                ('user_confirmed', models.BooleanField(default=False)),
                ('decision_note', models.TextField(blank=True)),
                ('excel_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='uploads.submissionexcelimport')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_engine.formfield')),
                ('grid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_engine.formgrid')),
                ('grid_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_engine.gridcolumn')),
            ],
            options={
                'ordering': ['source_sheet', 'source_row', 'source_column', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='excelimportmappingprofile',
            constraint=models.UniqueConstraint(fields=('provider', 'form_template', 'layout_fingerprint', 'version'), name='unique_excel_import_mapping_profile_version'),
        ),
        migrations.AddConstraint(
            model_name='submissionexcelimportmatch',
            constraint=models.UniqueConstraint(fields=('excel_import', 'source_locator'), name='unique_excel_import_source_locator'),
        ),
    ]
