"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, ArrowRight, Check, FileSpreadsheet } from "lucide-react";
import { api, ApiError } from "@/lib/api";
import type { DataCatalog, DataRequestItem, User } from "@/lib/types";

const STEPS=["Request details","Choose data","Review & send"];
const input="w-full rounded-xl border border-[#c3c6d0] bg-white px-3 py-2.5 text-sm";

export default function NewDataRequestPage(){
 const router=useRouter(); const params=useSearchParams(); const editId=params.get("edit"); const {data,isLoading}=useQuery<DataCatalog>({queryKey:["data-catalog"],queryFn:()=>api("/data-catalog/")});
 const {data:user}=useQuery<User>({queryKey:["me"],queryFn:()=>api("/auth/me/")});
 const {data:existing}=useQuery<DataRequestItem>({queryKey:["data-request",editId],queryFn:()=>api(`/data-requests/${editId}/`),enabled:!!editId});
 const [step,setStep]=useState(0); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 const [title,setTitle]=useState(""); const [purpose,setPurpose]=useState("");
 const [forms,setForms]=useState<number[]>([]); const [periods,setPeriods]=useState<number[]>([]); const [format,setFormat]=useState<"CSV"|"XLSX"|"PDF">("XLSX");
 const [providerScope,setProviderScope]=useState<"ALL"|"SECTOR"|"CATEGORY"|"SELECTED">("ALL"); const [sector,setSector]=useState(""); const [category,setCategory]=useState(""); const [providers,setProviders]=useState<number[]>([]);
 useEffect(()=>{const id=Number(params.get("form")); if(id) setForms([id]);},[params]);
 useEffect(()=>{if(!existing)return;setTitle(existing.title);setPurpose(existing.purpose);setForms(existing.scope.form_template_ids);setPeriods(existing.scope.period_ids);setFormat(existing.requested_format);setProviderScope(existing.scope.provider_scope);setSector(existing.scope.sector);setCategory(existing.scope.provider_category);setProviders(existing.scope.provider_ids)},[existing]);
 const availablePeriods=useMemo(()=>{if(!data) return []; if(!forms.length) return data.periods; const ids=new Set(data.forms.filter(f=>forms.includes(f.id)).flatMap(f=>f.available_period_ids)); return data.periods.filter(p=>ids.has(p.id));},[data,forms]);
 function validate(){setError(""); if(step===0&&(!title.trim()||!purpose.trim())){setError("Complete the request title and purpose to continue.");return false;} if(step===0&&(!user?.division||!user.grade)){setError("Ask an Administrator to assign your division and grade before requesting data.");return false;} if(step===1&&(!forms.length||!periods.length)){setError("Choose at least one dataset and reporting period.");return false;} if(step===1&&providerScope==="SECTOR"&&!sector){setError("Choose a sector.");return false;} if(step===1&&providerScope==="CATEGORY"&&!category){setError("Choose a provider category.");return false;} if(step===1&&providerScope==="SELECTED"&&!providers.length){setError("Choose at least one provider.");return false;} return true;}
 async function submit(){setBusy(true);setError("");try{const body={title,purpose,requested_format:format,scope:{form_template_ids:forms,period_ids:periods,all_fields:true,field_ids:[],grid_column_ids:[],provider_scope:providerScope,sector,provider_category:category,provider_ids:providers}};if(editId){await api.patch(`/data-requests/${editId}/`,body);await api.post(`/data-requests/${editId}/resubmit/`)}else await api.post("/data-requests/",body);router.push("/data-requests?created=1");}catch(e){setError(e instanceof ApiError?e.message:"Could not submit the request.");}finally{setBusy(false)}}
 if(isLoading)return <div className="mx-auto max-w-4xl rounded-2xl bg-white p-8 text-sm text-[#737780]">Loading request options…</div>;
 return <div className="mx-auto max-w-4xl space-y-6"><div><button onClick={()=>router.back()} className="flex items-center gap-2 text-sm text-[#0066cc]"><ArrowLeft size={16}/> Back</button><h1 className="mt-3 text-3xl font-semibold">{editId?"Update request":"Request data"}</h1><p className="mt-1 text-sm text-[#737780]">Three short steps. You can track everything in My Requests.</p></div>
 <ol className="grid grid-cols-3 overflow-hidden rounded-2xl border bg-white">{STEPS.map((label,i)=><li key={label} className={`flex items-center gap-2 border-r p-4 text-sm last:border-r-0 ${i===step?"bg-[#e8f1fb] font-semibold text-[#004999]":i<step?"text-[#1f7a4d]":"text-[#737780]"}`}><span className={`flex h-6 w-6 items-center justify-center rounded-full text-xs ${i<=step?"bg-[#0066cc] text-white":"bg-[#eceef0]"}`}>{i<step?<Check size={14}/>:i+1}</span><span className="hidden sm:inline">{label}</span></li>)}</ol>
 <section className="rounded-2xl border border-[#e6e8ea] bg-white p-6 md:p-8">
 {step===0&&<div className="space-y-5"><div><h2 className="text-xl font-semibold">Tell us what you need</h2><p className="text-sm text-[#737780]">This helps RIPS understand and review your request.</p></div><label className="block text-sm font-medium">Short request title<input className={`${input} mt-1.5`} value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Q2 market performance data"/></label><div className="grid gap-3 rounded-xl bg-[#f7f9fb] p-4 text-sm sm:grid-cols-2"><div><p className="text-xs uppercase text-[#737780]">Assigned division</p><p className="mt-1 font-semibold">{user?.division?.name??"Not assigned"}</p></div><div><p className="text-xs uppercase text-[#737780]">Grade</p><p className="mt-1 font-semibold">{user?.grade||"Not assigned"}</p></div></div><label className="block text-sm font-medium">How will you use the data?<textarea className={`${input} mt-1.5 min-h-28`} value={purpose} onChange={e=>setPurpose(e.target.value)} placeholder="Briefly explain the analysis, report, or decision this supports."/></label></div>}
 {step===1&&<div className="space-y-6"><div><h2 className="text-xl font-semibold">Choose the data</h2><p className="text-sm text-[#737780]">All available fields are included automatically.</p></div><div><p className="mb-2 text-sm font-medium">Datasets</p><div className="grid gap-2 sm:grid-cols-2">{data?.forms.map(f=><label key={f.id} className={`cursor-pointer rounded-xl border p-4 ${forms.includes(f.id)?"border-[#0066cc] bg-[#f4f8fd]":"border-[#e6e8ea]"}`}><input type="checkbox" className="mr-2" checked={forms.includes(f.id)} onChange={()=>{setForms(v=>v.includes(f.id)?v.filter(x=>x!==f.id):[...v,f.id]);setPeriods([])}}/><span className="text-sm font-semibold">{f.name}</span><p className="ml-6 mt-1 text-xs text-[#737780]">{f.code} • {f.frequency.replace("_"," ")}</p></label>)}</div></div><div><p className="mb-2 text-sm font-medium">Reporting periods</p><div className="flex flex-wrap gap-2">{availablePeriods.map(p=><button type="button" key={p.id} onClick={()=>setPeriods(v=>v.includes(p.id)?v.filter(x=>x!==p.id):[...v,p.id])} className={`rounded-full border px-3 py-2 text-sm ${periods.includes(p.id)?"border-[#0066cc] bg-[#0066cc] text-white":"bg-white"}`}>{p.name}</button>)}</div>{forms.length>0&&availablePeriods.length===0&&<p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-800">This dataset has no approved reporting periods yet.</p>}</div><label className="block text-sm font-medium">Which providers?<select className={`${input} mt-1.5`} value={providerScope} onChange={e=>setProviderScope(e.target.value as typeof providerScope)}><option value="ALL">All applicable providers</option><option value="SECTOR">One sector</option><option value="CATEGORY">One provider category</option><option value="SELECTED">Selected providers</option></select></label>{providerScope==="SECTOR"&&<select className={input} value={sector} onChange={e=>setSector(e.target.value)}><option value="">Choose sector</option>{data?.sectors.map(x=><option key={x}>{x}</option>)}</select>}{providerScope==="CATEGORY"&&<select className={input} value={category} onChange={e=>setCategory(e.target.value)}><option value="">Choose category</option>{data?.provider_categories.map(x=><option key={x}>{x}</option>)}</select>}{providerScope==="SELECTED"&&<div className="grid max-h-48 gap-2 overflow-y-auto rounded-xl border p-3">{data?.providers.map(p=><label key={p.id} className="text-sm"><input type="checkbox" className="mr-2" checked={providers.includes(p.id)} onChange={()=>setProviders(v=>v.includes(p.id)?v.filter(x=>x!==p.id):[...v,p.id])}/>{p.name}</label>)}</div>}</div>}
 {step===2&&<div className="space-y-6"><div><h2 className="text-xl font-semibold">Review and send</h2><p className="text-sm text-[#737780]">RIPS will confirm a delivery date after review starts.</p></div><div className="grid gap-3 rounded-xl bg-[#f7f9fb] p-5 text-sm sm:grid-cols-2"><div><p className="text-[#737780]">Request</p><p className="font-semibold">{title}</p></div><div><p className="text-[#737780]">Division and grade</p><p className="font-semibold">{user?.division?.name??existing?.requesting_division??"Not assigned"} · {user?.grade||existing?.requester_grade_snapshot||"Not assigned"}</p></div><div><p className="text-[#737780]">Datasets</p><p className="font-semibold">{forms.length} selected</p></div><div><p className="text-[#737780]">Periods</p><p className="font-semibold">{periods.length} selected</p></div></div><div><p className="mb-2 text-sm font-medium">Download format</p><div className="grid grid-cols-3 gap-3">{(["CSV","XLSX","PDF"] as const).map(x=><button type="button" key={x} onClick={()=>setFormat(x)} className={`rounded-xl border p-4 text-sm font-semibold ${format===x?"border-[#0066cc] bg-[#e8f1fb] text-[#004999]":""}`}><FileSpreadsheet className="mx-auto mb-2" size={20}/>{x}</button>)}</div></div></div>}
 {error&&<p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
 <div className="mt-8 flex justify-between border-t pt-5"><button type="button" disabled={step===0} onClick={()=>{setError("");setStep(s=>s-1)}} className="rounded-xl border px-5 py-2.5 text-sm font-semibold disabled:opacity-30">Back</button>{step<2?<button type="button" onClick={()=>validate()&&setStep(s=>s+1)} className="flex items-center gap-2 rounded-xl bg-[#001836] px-5 py-2.5 text-sm font-semibold text-white">Continue <ArrowRight size={16}/></button>:<button type="button" disabled={busy} onClick={submit} className="rounded-xl bg-[#0066cc] px-6 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy?"Sending…":editId?"Save and resubmit":"Submit request"}</button>}</div></section></div>
}
