"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, Clock3, Download, FileText, MessageSquare, Plus, XCircle } from "lucide-react";
import { api, downloadAuthenticated, ApiError } from "@/lib/api";
import type { DataRequestItem, PaginatedResponse, User } from "@/lib/types";

const labels:Record<string,string>={SUBMITTED:"Submitted",UNDER_REVIEW:"Under review",CHANGES_REQUESTED:"Changes needed",APPROVED:"Approved",PREPARING:"Preparing file",READY:"Ready to download",GENERATION_FAILED:"File needs retry",REJECTED:"Not approved",WITHDRAWN:"Withdrawn",EXPIRED:"Expired"};
const colors:Record<string,string>={READY:"bg-green-100 text-green-800",REJECTED:"bg-red-100 text-red-800",CHANGES_REQUESTED:"bg-amber-100 text-amber-800",GENERATION_FAILED:"bg-red-100 text-red-800",UNDER_REVIEW:"bg-blue-100 text-blue-800",PREPARING:"bg-blue-100 text-blue-800"};
function statusStep(status:string){if(["SUBMITTED","CHANGES_REQUESTED"].includes(status))return 0;if(["UNDER_REVIEW","REJECTED","WITHDRAWN"].includes(status))return 1;if(["APPROVED","PREPARING","GENERATION_FAILED"].includes(status))return 2;if(["READY","EXPIRED"].includes(status))return 3;return 0}
function formatBytes(value:number){if(value<1024)return `${value} B`;if(value<1048576)return `${(value/1024).toFixed(1)} KB`;return `${(value/1048576).toFixed(1)} MB`}

export default function RequestsPage(){
 const qc=useQueryClient(); const {data:user}=useQuery<User>({queryKey:["me"],queryFn:()=>api("/auth/me/")}); const admin=user?.role==="NCA_ADMIN";
 const {data,isLoading,error}=useQuery<PaginatedResponse<DataRequestItem>|DataRequestItem[]>({queryKey:["data-requests",admin],queryFn:()=>api("/data-requests/")});
 const requests=useMemo(()=>Array.isArray(data)?data:data?.results??[],[data]); const [selected,setSelected]=useState<string>();
 useEffect(()=>{if(!selected&&requests.length)setSelected(requests[0].id)},[requests,selected]); const item=requests.find(r=>r.id===selected);
 async function refresh(){await qc.invalidateQueries({queryKey:["data-requests"]})}
 return <div className="mx-auto max-w-7xl space-y-6"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-[#0066cc]">{admin?"ADMIN REVIEW":"MY REQUESTS"}</p><h1 className="mt-1 text-3xl font-semibold">{admin?"Data requests":"Request and receive data"}</h1><p className="mt-1 text-sm text-[#737780]">{admin?"Review purpose and scope, then make one clear decision.":"See progress, respond to changes, and download approved files."}</p></div>{!admin&&<Link href="/data-requests/new" className="flex items-center gap-2 rounded-xl bg-[#001836] px-4 py-2.5 text-sm font-semibold text-white"><Plus size={16}/> New request</Link>}</div>
 {isLoading&&<div className="rounded-2xl bg-white p-8 text-sm text-[#737780]">Loading requests…</div>}{error&&<div className="rounded-2xl bg-red-50 p-5 text-sm text-red-700">Requests could not be loaded.</div>}
 {!isLoading&&!requests.length&&<div className="rounded-2xl border bg-white p-12 text-center"><FileText className="mx-auto text-[#737780]"/><h2 className="mt-3 font-semibold">No requests yet</h2>{!admin&&<Link href="/data-requests/new" className="mt-4 inline-block text-sm font-semibold text-[#0066cc]">Create your first request</Link>}</div>}
 {!!requests.length&&<div className="grid gap-5 lg:grid-cols-[360px_1fr]"><div className="space-y-2">{requests.map(r=><button key={r.id} onClick={()=>setSelected(r.id)} className={`w-full rounded-2xl border bg-white p-4 text-left ${selected===r.id?"border-[#0066cc] ring-2 ring-[#0066cc]/10":"border-[#e6e8ea]"}`}><div className="flex items-start justify-between gap-3"><p className="font-semibold">{r.title}</p><span className={`shrink-0 rounded-full px-2 py-1 text-[10px] font-semibold ${colors[r.status]??"bg-gray-100 text-gray-700"}`}>{labels[r.status]}</span></div><p className="mt-2 text-xs text-[#737780]">{admin?`${r.requester_name} • ${r.requesting_division}`:new Date(r.submitted_at).toLocaleDateString()}</p></button>)}</div>{item&&<RequestDetail item={item} admin={admin} refresh={refresh}/>}</div>}
 </div>
}

function RequestDetail({item,admin,refresh}:{item:DataRequestItem;admin:boolean;refresh:()=>Promise<void>}){
 const [note,setNote]=useState(""); const [due,setDue]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const stage=statusStep(item.status);
 async function action(name:string,body?:unknown){setBusy(true);setError("");try{await api.post(`/data-requests/${item.id}/${name}/`,body);await refresh()}catch(e){setError(e instanceof ApiError?e.message:"Action failed.")}finally{setBusy(false)}}
 return <section className="rounded-2xl border border-[#e6e8ea] bg-white p-6 md:p-8"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-2xl font-semibold">{item.title}</h2><p className="mt-1 text-sm text-[#737780]">{item.requesting_division} • {item.requested_format}</p></div><span className={`rounded-full px-3 py-1.5 text-xs font-semibold ${colors[item.status]??"bg-gray-100 text-gray-700"}`}>{labels[item.status]}</span></div>
 {!admin&&<div className="mt-7"><div className="grid grid-cols-4">{["Submitted","Review","Preparing","Ready"].map((x,i)=><div key={x} className="text-center"><div className={`mx-auto flex h-8 w-8 items-center justify-center rounded-full text-xs font-bold ${i<=stage?"bg-[#0066cc] text-white":"bg-[#eceef0] text-[#737780]"}`}>{i<stage?<CheckCircle2 size={16}/>:i+1}</div><p className="mt-2 text-xs font-medium">{x}</p></div>)}</div><div className="relative -z-0 mx-[12.5%] -mt-[48px] mb-12 h-0.5 bg-[#e6e8ea]"/></div>}
 {item.decision_note&&<div className="mt-5 rounded-xl bg-amber-50 p-4"><p className="text-xs font-semibold uppercase text-amber-800">Message from RIPS</p><p className="mt-1 text-sm text-amber-900">{item.decision_note}</p></div>}
 <div className="mt-6 grid gap-4 sm:grid-cols-2"><div><p className="text-xs uppercase text-[#737780]">Purpose</p><p className="mt-1 text-sm">{item.purpose}</p></div><div><p className="text-xs uppercase text-[#737780]">Requested by</p><p className="mt-1 text-sm">{item.requester_name}<br/>{item.requester_email}<br/>{item.requesting_division} · {item.requester_grade_snapshot||"Grade not recorded"}</p></div><div><p className="text-xs uppercase text-[#737780]">Data selection</p><p className="mt-1 text-sm">{item.scope.form_template_ids.length} dataset(s), {item.scope.period_ids.length} period(s)</p></div><div><p className="text-xs uppercase text-[#737780]">Expected delivery</p><p className="mt-1 text-sm">{item.expected_delivery_at?new Date(item.expected_delivery_at).toLocaleDateString():"Set when review starts"}</p></div></div>
 {item.artifact&&<div className="mt-6 rounded-xl border border-[#d9e6f2] bg-[#f4f8fd] p-4"><p className="text-xs font-semibold uppercase text-[#004999]">Released file</p><div className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><p><span className="text-[#737780]">Format:</span> {item.requested_format}</p><p><span className="text-[#737780]">Rows:</span> {item.artifact.row_count.toLocaleString()}</p><p><span className="text-[#737780]">Size:</span> {formatBytes(item.artifact.file_size)}</p><p><span className="text-[#737780]">Expires:</span> {new Date(item.artifact.expires_at).toLocaleDateString()}</p><p className="break-all sm:col-span-2"><span className="text-[#737780]">SHA-256:</span> <span className="font-mono text-xs">{item.artifact.sha256}</span></p></div>{item.status==="READY"&&!item.artifact.is_expired&&<button onClick={()=>downloadAuthenticated(`/data-requests/${item.id}/download/`,{},item.artifact?.filename??`request-${item.id}.${item.requested_format.toLowerCase()}`)} className="mt-4 flex items-center gap-2 rounded-xl bg-[#0066cc] px-5 py-2.5 text-sm font-semibold text-white"><Download size={16}/> {admin?"Download released file":"Download file"}</button>}</div>}
 {error&&<p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
 {!admin&&<div className="mt-7 flex flex-wrap gap-3">{item.status==="READY"&&!item.artifact&&<button onClick={()=>downloadAuthenticated(`/data-requests/${item.id}/download/`,{},`request-${item.id}.${item.requested_format.toLowerCase()}`)} className="flex items-center gap-2 rounded-xl bg-[#0066cc] px-5 py-2.5 text-sm font-semibold text-white"><Download size={16}/> Download file</button>}{item.status==="CHANGES_REQUESTED"&&<><Link href={`/data-requests/new?edit=${item.id}`} className="rounded-xl bg-[#001836] px-5 py-2.5 text-sm font-semibold text-white">Update request</Link><button disabled={busy} onClick={()=>action("resubmit")} className="rounded-xl border px-5 py-2.5 text-sm font-semibold">Resubmit</button></>}{["SUBMITTED","UNDER_REVIEW","CHANGES_REQUESTED"].includes(item.status)&&<button disabled={busy} onClick={()=>action("withdraw")} className="rounded-xl border border-red-200 px-5 py-2.5 text-sm font-semibold text-red-700">Withdraw</button>}</div>}
 {admin&&<div className="mt-8 border-t pt-6"><h3 className="text-lg font-semibold">Decision</h3>{item.status==="SUBMITTED"&&<div className="mt-4 max-w-md"><label className="text-sm font-medium">Expected delivery date<input type="date" min={new Date(Date.now()+86400000).toISOString().slice(0,10)} value={due} onChange={e=>setDue(e.target.value)} className="mt-1.5 w-full rounded-xl border px-3 py-2.5 text-sm"/></label><button disabled={busy||!due} onClick={()=>action("start-review",{expected_delivery_at:new Date(`${due}T17:00:00`).toISOString()})} className="mt-3 flex items-center gap-2 rounded-xl bg-[#001836] px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-40"><Clock3 size={16}/> Start review</button></div>}{item.status==="UNDER_REVIEW"&&<div className="mt-4 space-y-4"><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a reason when asking for changes or rejecting" className="min-h-24 w-full rounded-xl border p-3 text-sm"/><div className="flex flex-wrap gap-3"><button disabled={busy} onClick={()=>action("approve")} className="flex items-center gap-2 rounded-xl bg-[#1f7a4d] px-5 py-2.5 text-sm font-semibold text-white"><CheckCircle2 size={16}/> Approve</button><button disabled={busy} onClick={()=>action("request-changes",{note})} className="flex items-center gap-2 rounded-xl border border-amber-300 px-5 py-2.5 text-sm font-semibold text-amber-800"><MessageSquare size={16}/> Ask for changes</button><button disabled={busy} onClick={()=>action("reject",{note})} className="flex items-center gap-2 rounded-xl border border-red-300 px-5 py-2.5 text-sm font-semibold text-red-700"><XCircle size={16}/> Reject</button></div></div>}{item.status==="GENERATION_FAILED"&&<button disabled={busy} onClick={()=>action("retry-generation")} className="mt-4 rounded-xl bg-[#001836] px-5 py-2.5 text-sm font-semibold text-white">Retry file generation</button>}{!["SUBMITTED","UNDER_REVIEW","GENERATION_FAILED"].includes(item.status)&&<p className="mt-3 text-sm text-[#737780]">No action is required for this request.</p>}</div>}
 <details className="mt-8 border-t pt-5"><summary className="cursor-pointer text-sm font-semibold text-[#0066cc]">View request history</summary><div className="mt-4 space-y-3">{item.events.map(e=><div key={e.id} className="border-l-2 border-[#c3c6d0] pl-4"><p className="text-sm font-medium">{e.message}</p><p className="text-xs text-[#737780]">{new Date(e.created_at).toLocaleString()} • {e.actor_name||"System"}</p></div>)}</div></details>
 </section>
}
