"use client";

import { Fragment, useMemo, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { CheckCircle2, ChevronDown, ChevronRight, RefreshCw, ShieldAlert } from "lucide-react";
import { api } from "@/lib/api";
import { Skeleton } from "@/components/ui/Skeleton";
import { formatDateTime } from "@/lib/utils";
import type { AuditAnchor, AuditEvent, PaginatedResponse, User } from "@/lib/types";

type ChainStatus = { valid:boolean; problem_event_ids:number[]; event_count:number };

function Metadata({ value }: { value:unknown }) {
  if (value == null) return <span className="text-[#9aa0a6]">None</span>;
  return <pre className="max-h-72 overflow-auto whitespace-pre-wrap break-all rounded-lg bg-[#f7f9fb] p-3 text-[11px] leading-5 text-[#43474f]">{JSON.stringify(value,null,2)}</pre>;
}

export default function AuditLogPage() {
  const [filters,setFilters]=useState({search:"",user:"",role:"",organization:"",action:"",entity_type:"",date_from:"",date_to:""});
  const [page,setPage]=useState(1);
  const [expanded,setExpanded]=useState<number|null>(null);
  const me=useQuery<User>({queryKey:["me"],queryFn:()=>api("/auth/me/"),staleTime:300_000});
  const query=useMemo(()=>{const p=new URLSearchParams({page:String(page)});Object.entries(filters).forEach(([key,value])=>{if(value.trim())p.set(key,value.trim())});return p.toString()},[filters,page]);
  const events=useQuery<PaginatedResponse<AuditEvent>>({queryKey:["audit-events",query],queryFn:()=>api(`/audit/?${query}`),enabled:me.data?.role==="NCA_ADMIN"});
  const anchors=useQuery<AuditAnchor[]>({queryKey:["audit-anchors"],queryFn:()=>api("/audit/anchors/"),enabled:me.data?.role==="NCA_ADMIN"});
  const verify=useMutation<ChainStatus>({mutationFn:()=>api("/audit/verify/")});
  const update=(key:keyof typeof filters,value:string)=>{setFilters(current=>({...current,[key]:value}));setPage(1)};
  if(me.isLoading)return <Skeleton className="h-40 w-full"/>;
  if(me.data?.role!=="NCA_ADMIN")return <div className="rounded-xl border border-red-200 bg-red-50 p-5 text-sm text-red-800"><p className="font-semibold">Access restricted</p><p className="mt-1">Only NCA Administrators can view the Audit Log.</p></div>;
  return <div className="space-y-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-[28px] font-semibold">Audit Log</h1><p className="mt-1 text-sm text-[#43474f]">Immutable, hash-chained records of security-relevant and state-changing activity.</p></div><button onClick={()=>verify.mutate()} disabled={verify.isPending} className="inline-flex items-center gap-2 rounded-lg bg-[#002d5b] px-4 py-2.5 text-sm font-semibold text-white"><RefreshCw size={16} className={verify.isPending?"animate-spin":""}/>Verify audit chain</button></div>
    <section className="grid gap-4 sm:grid-cols-3"><article className="rounded-2xl border bg-white p-5"><p className="text-xs font-semibold uppercase text-[#737780]">Recorded events</p><p className="mt-2 text-3xl font-bold">{events.data?.count??"—"}</p></article><article className="rounded-2xl border bg-white p-5"><p className="text-xs font-semibold uppercase text-[#737780]">Chain status</p><div className="mt-2 flex items-center gap-2">{verify.data?(verify.data.valid?<CheckCircle2 className="text-green-700"/>:<ShieldAlert className="text-red-700"/>):null}<p className="text-lg font-semibold">{verify.data?(verify.data.valid?"Verified":"Problems detected"):"Not verified this session"}</p></div></article><article className="rounded-2xl border bg-white p-5"><p className="text-xs font-semibold uppercase text-[#737780]">Latest anchor</p><p className="mt-2 text-lg font-semibold">{anchors.data?.[0]?.anchor_date??"No anchor"}</p><p className="mt-1 text-xs text-[#737780]">{anchors.data?.[0]?`${anchors.data[0].event_count} anchored event(s)`:"Daily anchors appear here when available."}</p></article></section>
    {verify.data&&!verify.data.valid&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">Audit verification failed at event IDs: {verify.data.problem_event_ids.join(", ")}</div>}
    <section className="rounded-2xl border bg-white p-5"><div className="grid gap-3 md:grid-cols-4"><input value={filters.search} onChange={e=>update("search",e.target.value)} placeholder="Search audit records" className="rounded-lg border px-3 py-2 text-sm"/><input value={filters.user} onChange={e=>update("user",e.target.value)} placeholder="User email" className="rounded-lg border px-3 py-2 text-sm"/><select value={filters.role} onChange={e=>update("role",e.target.value)} className="rounded-lg border bg-white px-3 py-2 text-sm"><option value="">All roles</option><option value="NCA_ADMIN">NCA Admin</option><option value="NCA_OFFICER">NCA Officer</option><option value="PROVIDER_DATA_ENTRY">Provider Data Entry</option><option value="PROVIDER_APPROVER">Provider Approver</option></select><input value={filters.organization} onChange={e=>update("organization",e.target.value)} placeholder="Organization" className="rounded-lg border px-3 py-2 text-sm"/><input value={filters.action} onChange={e=>update("action",e.target.value)} placeholder="Action" className="rounded-lg border px-3 py-2 text-sm"/><input value={filters.entity_type} onChange={e=>update("entity_type",e.target.value)} placeholder="Entity type" className="rounded-lg border px-3 py-2 text-sm"/><label className="text-xs text-[#737780]">From<input type="date" value={filters.date_from} onChange={e=>update("date_from",e.target.value)} className="mt-1 block w-full rounded-lg border px-3 py-2 text-sm text-[#191c1e]"/></label><label className="text-xs text-[#737780]">To<input type="date" value={filters.date_to} onChange={e=>update("date_to",e.target.value)} className="mt-1 block w-full rounded-lg border px-3 py-2 text-sm text-[#191c1e]"/></label></div></section>
    <section className="overflow-hidden rounded-2xl border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left"><thead className="border-b bg-[#f7f9fb] text-xs uppercase text-[#43474f]"><tr><th className="p-4">Timestamp</th><th className="p-4">Actor</th><th className="p-4">Role / organization</th><th className="p-4">Action</th><th className="p-4">Entity</th><th className="p-4">IP address</th><th className="p-4"></th></tr></thead><tbody className="divide-y">{events.isLoading?Array.from({length:6}).map((_,i)=><tr key={i}><td colSpan={7} className="p-4"><Skeleton className="h-5"/></td></tr>):events.isError?<tr><td colSpan={7} className="p-10 text-center text-sm text-red-700">Audit records could not be loaded. <button onClick={()=>events.refetch()} className="font-semibold text-[#0066cc]">Retry</button></td></tr>:events.data?.results.length?events.data.results.map(item=><Fragment key={item.id}><tr className="align-top"><td className="whitespace-nowrap p-4 text-xs">{formatDateTime(item.timestamp)}</td><td className="p-4 text-sm">{item.user_email||"System / unknown"}</td><td className="p-4 text-xs"><p>{item.role||"System"}</p><p className="text-[#737780]">{item.organization||"—"}</p></td><td className="p-4 text-sm font-semibold">{item.action.replaceAll("_"," ")}</td><td className="p-4 text-xs"><p>{item.entity_type}</p><p className="font-mono text-[#737780]">{item.entity_id}</p></td><td className="p-4 text-xs">{item.ip_address||"—"}</td><td className="p-4"><button aria-label={`Show metadata for event ${item.id}`} onClick={()=>setExpanded(expanded===item.id?null:item.id)}>{expanded===item.id?<ChevronDown size={17}/>:<ChevronRight size={17}/>}</button></td></tr>{expanded===item.id&&<tr><td colSpan={7} className="bg-[#fbfcfd] p-4"><div className="grid gap-4 md:grid-cols-2"><div><p className="mb-2 text-xs font-semibold uppercase text-[#737780]">Before</p><Metadata value={item.before_value}/></div><div><p className="mb-2 text-xs font-semibold uppercase text-[#737780]">After</p><Metadata value={item.after_value}/></div></div><p className="mt-3 break-all font-mono text-[10px] text-[#737780]">Hash: {item.event_hash}</p></td></tr>}</Fragment>):<tr><td colSpan={7} className="p-10 text-center text-sm text-[#737780]">No audit events match these filters.</td></tr>}</tbody></table></div><div className="flex items-center justify-between border-t px-5 py-3 text-sm"><button disabled={!events.data?.previous} onClick={()=>setPage(value=>Math.max(1,value-1))} className="font-semibold text-[#0066cc] disabled:text-[#9aa0a6]">Previous</button><span>Page {page}</span><button disabled={!events.data?.next} onClick={()=>setPage(value=>value+1)} className="font-semibold text-[#0066cc] disabled:text-[#9aa0a6]">Next</button></div></section>
  </div>;
}
