"use client";

import { useQuery } from "@tanstack/react-query";
import { Suspense, useMemo } from "react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { AlertTriangle, ArrowRight, CheckCircle2, ClipboardCheck, Clock3, FileText, Banknote, TrendingUp } from "lucide-react";
import { api } from "@/lib/api";
import { WorkflowBadge, DueStateBadge } from "@/components/ui/Badge";
import { Skeleton } from "@/components/ui/Skeleton";
import type { ExpectedSubmission, PaginatedResponse, ProviderWorkspaceSummary, User } from "@/lib/types";

function displayDate(value: string | null) {
  return value ? new Date(value).toLocaleDateString("en-GB", { day:"numeric", month:"short", year:"numeric" }) : "—";
}

function MetricCard({ label, value, detail, icon:Icon, tone="blue" }: { label:string; value:string|number; detail:string; icon:typeof FileText; tone?:"blue"|"green"|"amber"|"red" }) {
  const tones={blue:"bg-[#e8f1fb] text-[#004999]",green:"bg-[#e5f4ec] text-[#137333]",amber:"bg-[#fff3d6] text-[#805500]",red:"bg-[#ffe8e8] text-[#b3261e]"};
  return <article className="dashboard-surface p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold text-[#43474f]">{label}</p><p className="mt-2 text-3xl font-bold tabular-nums text-[#191c1e]">{value}</p></div><span className={`rounded-xl p-2.5 ${tones[tone]}`}><Icon size={20}/></span></div><p className="mt-3 text-xs leading-5 text-[#43474f]">{detail}</p></article>;
}

function SubmissionRow({ row }: { row:ExpectedSubmission }) {
  return <article className="grid gap-4 px-5 py-4 transition-colors hover:bg-[#f9fbfd] md:grid-cols-[1fr_150px_auto] md:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-[#191c1e]">{row.form_name}</h3><WorkflowBadge status={row.workflow_status}/><DueStateBadge state={row.due_state}/>{row.open_compliance_flag_count>0&&<span className="rounded-full bg-[#fff0c2] px-2 py-0.5 text-[10px] font-semibold text-[#6b4800]">{row.open_compliance_flag_count} flag{row.open_compliance_flag_count===1?"":"s"}</span>}</div><p className="mt-1 text-xs text-[#737780]">{row.form_code} · {row.period_name} · Due {displayDate(row.effective_due_at)}</p>{row.form_reference&&<p className="mt-1 break-all font-mono text-[10px] text-[#004999]">{row.form_reference}</p>}<p className="mt-2 text-xs text-[#43474f]">Last edited by {row.last_edited_by_name||"No one yet"}{row.last_edited_at?` · ${new Date(row.last_edited_at).toLocaleString()}`:""}</p></div><div><div className="flex items-center justify-between text-xs"><span className="text-[#737780]">Completion</span><strong className="tabular-nums text-[#191c1e]">{Number(row.completion_pct).toFixed(0)}%</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#e8eaed]"><div className="h-full rounded-full bg-[#0066cc]" style={{width:`${Math.max(0,Math.min(100,Number(row.completion_pct)))}%`}}/></div>{row.open_correction_count>0&&<p className="mt-2 text-[10px] font-medium text-[#9b6200]">{row.open_correction_count} open flagged return{row.open_correction_count===1?"":"s"}</p>}</div><Link href={`/provider/forms/${row.id}`} className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#002d5b] px-4 py-2 text-sm font-semibold text-white">{row.permitted_actions.includes("EDIT")?"Open and work":"Review"}<ArrowRight size={14}/></Link></article>;
}

function ProviderDashboardContent() {
  const searchParams=useSearchParams();
  const attentionRequired=searchParams.get("attention_required")==="true";
  const {data:user}=useQuery<User>({queryKey:["me"],queryFn:()=>api("/auth/me/"),staleTime:300_000});
  const isApprover=user?.role==="PROVIDER_APPROVER";
  const summaryQ=useQuery<ProviderWorkspaceSummary>({queryKey:["provider-workspace-summary"],queryFn:()=>api("/provider-workspace/summary/")});
  const allQ=useQuery<PaginatedResponse<ExpectedSubmission>>({queryKey:["provider-workspace","dashboard-all"],queryFn:()=>api("/provider-workspace/submissions/?queue=all&ordering=period__due_at&page_size=100")});
  const actionQ=useQuery<PaginatedResponse<ExpectedSubmission>>({queryKey:["provider-workspace",attentionRequired?"compliance_attention":"action_required"],queryFn:()=>api(`/provider-workspace/submissions/?queue=${attentionRequired?"all&attention_required=true":"action_required"}&ordering=period__due_at&page_size=20`)});
  const awaitingQ=useQuery<PaginatedResponse<ExpectedSubmission>>({queryKey:["provider-workspace","awaiting_data_entry"],queryFn:()=>api("/provider-workspace/submissions/?queue=awaiting_data_entry&ordering=period__due_at&page_size=20"),enabled:isApprover});
  const summary=summaryQ.data;
  const allRows=useMemo(()=>allQ.data?.results??[],[allQ.data]);
  const averageCompletion=allRows.length?Math.round(allRows.reduce((sum,row)=>sum+Number(row.completion_pct),0)/allRows.length):0;
  const completedCount=allRows.filter(row=>["SUBMITTED","UNDER_REVIEW","CORRECTION_REQUESTED","RESUBMITTED","APPROVED","REJECTED","ARCHIVED"].includes(row.workflow_status)).length;
  const workflow=[
    ["Not started",allRows.filter(row=>row.workflow_status==="NOT_STARTED").length,"bg-[#9aa0a6]"],
    ["In progress",allRows.filter(row=>["DRAFT","PROVIDER_CHANGES_REQUESTED"].includes(row.workflow_status)).length,"bg-[#0066cc]"],
    ["Internal review",allRows.filter(row=>["PENDING_APPROVAL","PROVIDER_RESUBMITTED"].includes(row.workflow_status)).length,"bg-[#7b61a8]"],
    ["With NCA",allRows.filter(row=>["SUBMITTED","UNDER_REVIEW","CORRECTION_REQUESTED","RESUBMITTED"].includes(row.workflow_status)).length,"bg-[#5b21b6]"],
    ["Completed",allRows.filter(row=>["APPROVED","REJECTED","ARCHIVED"].includes(row.workflow_status)).length,"bg-[#188038]"],
  ] as const;

  return <div className="space-y-6">
    <section className="border-b border-[#dfe5eb] pb-6 pt-2"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><h1 className="text-3xl font-semibold tracking-[-0.025em] text-[#001836]">Welcome back{user?.name?`, ${user.name}`:""}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#43474f]">Monitor regulatory returns, completion, deadlines, flags and approval work from one place.</p></div><div className="flex gap-6 md:text-right"><div><p className="text-2xl font-semibold tabular-nums text-[#002d5b]">{allRows.length}</p><p className="text-xs text-[#43474f]">Total forms</p></div><div><p className="text-2xl font-semibold tabular-nums text-[#002d5b]">{completedCount}</p><p className="text-xs text-[#43474f]">Submitted</p></div></div></div></section>
    {(summary?.overdue??0)>0&&<div className="flex items-center gap-3 rounded-xl border border-[#e31937]/30 bg-[#ffe8e8] px-5 py-4 text-sm text-[#9b1c1c]"><AlertTriangle size={20}/><p><strong>{summary?.overdue} overdue return{summary?.overdue===1?"":"s"}.</strong> Open the priority queue to review the deadline and next required step.</p></div>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{summaryQ.isLoading||allQ.isLoading?Array.from({length:4}).map((_,i)=><Skeleton key={i} className="h-36 rounded-2xl"/>):<><MetricCard label="Action required" value={summary?.action_required??0} detail={isApprover?"Returns requiring approval, review or follow-up":"Forms ready for data entry or revision"} icon={ClipboardCheck}/><MetricCard label="Penalty amount" value={`GH₵${Number(summary?.penalty_amount_ghs??0).toLocaleString("en-GH",{minimumFractionDigits:2,maximumFractionDigits:2})}`} detail={`${summary?.penalty_obligation_count??0} active obligation${(summary?.penalty_obligation_count??0)===1?"":"s"} with a penalty`} icon={Banknote} tone={Number(summary?.penalty_amount_ghs??0)>0?"amber":"green"}/><MetricCard label="Number of penalties" value={summary?.penalty_obligation_count??0} detail={(summary?.penalty_obligation_count??0)>0?"Active reporting obligations with an assigned penalty":"No penalties assigned"} icon={AlertTriangle} tone={(summary?.penalty_obligation_count??0)>0?"red":"green"}/><MetricCard label="Average completion" value={`${averageCompletion}%`} detail={`${allRows.length} active form${allRows.length===1?"":"s"} included in the calculation`} icon={TrendingUp} tone="green"/></>}</section>
    <section className="grid gap-5 lg:grid-cols-[1.25fr_0.75fr]"><article className="rounded-2xl border border-[#e6e8ea] bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-[#191c1e]">Submission health</h2><p className="mt-1 text-xs text-[#737780]">Each form is classified by its current workflow status</p></div><CheckCircle2 className="text-[#188038]" size={22}/></div><div className="mt-5 space-y-4">{workflow.map(([label,count,color])=><div key={label}><div className="flex justify-between text-xs"><span className="font-medium text-[#43474f]">{label}</span><span className="tabular-nums text-[#737780]">{count} of {allRows.length}</span></div><div className="mt-2 h-2.5 overflow-hidden rounded-full bg-[#eceef0]"><div className={`h-full rounded-full ${color}`} style={{width:`${allRows.length?Math.round(count/allRows.length*100):0}%`}}/></div></div>)}</div></article><article className="rounded-2xl border border-[#e6e8ea] bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-[#191c1e]">Workload snapshot</h2><p className="mt-1 text-xs text-[#737780]">Role-specific operational totals</p></div><Clock3 className="text-[#0066cc]" size={22}/></div><dl className="mt-5 divide-y divide-[#eceef0] text-sm">{(isApprover?[["Awaiting Data Entry",summary?.awaiting_data_entry??0],["Awaiting approval",summary?.awaiting_approver??0],["NCA flag review",summary?.nca_corrections??0],["Recently submitted",summary?.recently_submitted??0]]:[["Drafts",summary?.drafts??0],["Returned for updates",summary?.returned_to_data_entry??0],["Due soon",summary?.due_soon??0],["Overdue",summary?.overdue??0]]).map(([label,value])=><div key={label as string} className="flex items-center justify-between py-3"><dt className="text-[#43474f]">{label}</dt><dd className="rounded-full bg-[#f1f4f7] px-2.5 py-1 font-semibold tabular-nums text-[#002d5b]">{value}</dd></div>)}</dl></article></section>
    <section className="overflow-hidden rounded-2xl border border-[#e6e8ea] bg-white"><div className="flex items-center justify-between border-b border-[#eceef0] px-6 py-4"><div><h2 className="font-semibold text-[#191c1e]">{attentionRequired?"Flagged submissions":"Priority work queue"}</h2><p className="mt-1 text-xs text-[#737780]">{attentionRequired?"Submissions with unresolved compliance flags":"Items currently requiring action from your role"}</p></div>{isApprover&&<Link href="/provider/forms?provider_status=AWAITING_APPROVAL" className="inline-flex items-center gap-1 text-sm font-semibold text-[#0066cc]">Open Forms queue<ArrowRight size={14}/></Link>}</div>{actionQ.isLoading?<div className="space-y-3 p-6">{Array.from({length:3}).map((_,i)=><Skeleton key={i} className="h-24"/>)}</div>:!(actionQ.data?.results.length)?<div className="p-12 text-center"><CheckCircle2 className="mx-auto text-[#188038]"/><p className="mt-3 font-medium">Nothing needs your action</p><p className="mt-1 text-sm text-[#737780]">New drafts, approval work and flags will appear here.</p></div>:<div className="divide-y divide-[#eceef0]">{actionQ.data.results.map(row=><SubmissionRow key={row.id} row={row}/>)}</div>}</section>
    {isApprover&&<section className="overflow-hidden rounded-2xl border border-[#e6e8ea] bg-white"><div className="border-b border-[#eceef0] px-6 py-4"><h2 className="font-semibold text-[#191c1e]">Awaiting Data Entry</h2><p className="mt-1 text-xs text-[#737780]">New assignments being prepared by your Data Entry team</p></div>{awaitingQ.isLoading?<div className="p-6"><Skeleton className="h-24"/></div>:!(awaitingQ.data?.results.length)?<p className="p-10 text-center text-sm text-[#737780]">No forms are currently awaiting Data Entry.</p>:<div className="divide-y divide-[#eceef0]">{awaitingQ.data.results.slice(0,5).map(row=><SubmissionRow key={row.id} row={row}/>)}</div>}</section>}
  </div>;
}

export default function ProviderDashboardPage() {
  return <Suspense fallback={null}><ProviderDashboardContent/></Suspense>;
}
