# Generated by Django 5.0.6 on 2026-06-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Provider Approval'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under NCA Review'), ('CORRECTION_REQUESTED', 'Correction Requested'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='NOT_STARTED', max_length=30)),
                ('due_state', models.CharField(choices=[('NOT_OPEN', 'Not Open'), ('OPEN', 'Open'), ('DUE_SOON', 'Due Soon'), ('DUE_TODAY', 'Due Today'), ('OVERDUE', 'Overdue'), ('CLOSED', 'Closed')], default='NOT_OPEN', max_length=15)),
                ('due_at_override', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period__year', '-period__month'],
            },
        ),
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('SEMI_ANNUAL', 'Semi-Annual'), ('ANNUAL', 'Annual')], max_length=15)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('opens_at', models.DateTimeField()),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REQUEST_CORRECTION', 'Request Correction'), ('ADD_NOTE', 'Add Internal Note'), ('ADD_PROVIDER_COMMENT', 'Add Provider-Visible Comment')], max_length=30)),
                ('target_type', models.CharField(blank=True, choices=[('SUBMISSION', 'Submission'), ('SECTION', 'Section'), ('FIELD', 'Field'), ('GRID_CELL', 'Grid Cell')], max_length=15)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('is_provider_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('completion_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_row_id', models.CharField(blank=True, max_length=100)),
                ('value', models.TextField(blank=True)),
                ('value_status', models.CharField(choices=[('MISSING', 'Missing'), ('PROVIDED', 'Provided'), ('OPTIONAL_NOT_PROVIDED', 'Optional Not Provided'), ('NOT_APPLICABLE', 'Not Applicable'), ('NOT_AVAILABLE', 'Not Available'), ('NOT_REQUIRED', 'Not Required for Provider'), ('PENDING_CLARIFICATION', 'Pending Clarification'), ('WAITING_CORRECTION', 'Waiting for Correction'), ('SYSTEM_CALCULATED', 'System Calculated')], default='MISSING', max_length=30)),
                ('explanation', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
