# Generated by Django 5.0.6 on 2026-06-08 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms_engine', '0001_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('SEMI_ANNUAL', 'Semi-Annual'), ('ANNUAL', 'Annual')], max_length=15)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('opens_at', models.DateTimeField()),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_form_templates', models.ManyToManyField(blank=True, to='forms_engine.formtemplate')),
                ('assigned_providers', models.ManyToManyField(blank=True, to='providers.providerprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='ExpectedSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Provider Approval'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under NCA Review'), ('CORRECTION_REQUESTED', 'Correction Requested'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='NOT_STARTED', max_length=30)),
                ('due_state', models.CharField(choices=[('NOT_OPEN', 'Not Open'), ('OPEN', 'Open'), ('DUE_SOON', 'Due Soon'), ('DUE_TODAY', 'Due Today'), ('OVERDUE', 'Overdue'), ('CLOSED', 'Closed')], default='NOT_OPEN', max_length=15)),
                ('due_at_override', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_submissions', to=settings.AUTH_USER_MODEL)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_engine.formtemplate')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expected_submissions', to='providers.providerprofile')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expected_submissions', to='submissions.reportingperiod')),
            ],
            options={
                'ordering': ['-period__year', '-period__month'],
                'unique_together': {('provider', 'form_template', 'period')},
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('completion_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expected', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='submissions.expectedsubmission')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('expected', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REQUEST_CORRECTION', 'Request Correction'), ('ADD_NOTE', 'Add Internal Note'), ('ADD_PROVIDER_COMMENT', 'Add Provider-Visible Comment')], max_length=30)),
                ('target_type', models.CharField(blank=True, choices=[('SUBMISSION', 'Submission'), ('SECTION', 'Section'), ('FIELD', 'Field'), ('GRID_CELL', 'Grid Cell')], max_length=15)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('is_provider_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_actions', to='submissions.submission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_row_id', models.CharField(blank=True, max_length=100)),
                ('value', models.TextField(blank=True)),
                ('value_status', models.CharField(choices=[('MISSING', 'Missing'), ('PROVIDED', 'Provided'), ('OPTIONAL_NOT_PROVIDED', 'Optional Not Provided'), ('NOT_APPLICABLE', 'Not Applicable'), ('NOT_AVAILABLE', 'Not Available'), ('NOT_REQUIRED', 'Not Required for Provider'), ('PENDING_CLARIFICATION', 'Pending Clarification'), ('WAITING_CORRECTION', 'Waiting for Correction'), ('SYSTEM_CALCULATED', 'System Calculated')], default='MISSING', max_length=30)),
                ('explanation', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_engine.formfield')),
                ('grid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_engine.formgrid')),
                ('grid_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_engine.gridcolumn')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='submissions.submission')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['submission', 'field'], name='submissions_submiss_7e8845_idx'), models.Index(fields=['submission', 'grid', 'grid_row_id', 'grid_column'], name='submissions_submiss_e8419f_idx')],
            },
        ),
    ]
