# Generated by Django 5.0.6 on 2026-06-03 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms_engine', '0001_initial'),
        ('providers', '0002_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expectedsubmission',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expectedsubmission',
            name='form_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_engine.formtemplate'),
        ),
        migrations.AddField(
            model_name='expectedsubmission',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expected_submissions', to='providers.providerprofile'),
        ),
        migrations.AddField(
            model_name='reportingperiod',
            name='applicable_form_templates',
            field=models.ManyToManyField(blank=True, to='forms_engine.formtemplate'),
        ),
        migrations.AddField(
            model_name='reportingperiod',
            name='assigned_providers',
            field=models.ManyToManyField(blank=True, to='providers.providerprofile'),
        ),
        migrations.AddField(
            model_name='reportingperiod',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expectedsubmission',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expected_submissions', to='submissions.reportingperiod'),
        ),
        migrations.AddField(
            model_name='reviewaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='expected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='submissions.expectedsubmission'),
        ),
        migrations.AddField(
            model_name='submission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewaction',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_actions', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='submissionvalue',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_engine.formfield'),
        ),
        migrations.AddField(
            model_name='submissionvalue',
            name='grid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_engine.formgrid'),
        ),
        migrations.AddField(
            model_name='submissionvalue',
            name='grid_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_engine.gridcolumn'),
        ),
        migrations.AddField(
            model_name='submissionvalue',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='submissionvalue',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='expectedsubmission',
            unique_together={('provider', 'form_template', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('expected', 'version')},
        ),
        migrations.AddIndex(
            model_name='submissionvalue',
            index=models.Index(fields=['submission', 'field'], name='submissions_submiss_7e8845_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionvalue',
            index=models.Index(fields=['submission', 'grid', 'grid_row_id', 'grid_column'], name='submissions_submiss_e8419f_idx'),
        ),
    ]
