# Generated by Django 4.2.13 on 2026-08-05 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0004_formfamily_validationrule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='FULL', max_length=100)),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('WARN', 'Warnings'), ('FAIL', 'Failed')], max_length=10)),
                ('ruleset_snapshot', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_runs', to='submissions.submission')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=10)),
                ('target_type', models.CharField(max_length=20)),
                ('target_id', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_engine.validationrule')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='submissions.validationrun')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('private_path', models.CharField(max_length=500)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='submissions.submission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocker_ids', models.JSONField(default=list)),
                ('reason', models.TextField()),
                ('evidence_reference', models.CharField(blank=True, max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submission_overrides_approved', to=settings.AUTH_USER_MODEL)),
                ('expected_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_overrides', to='submissions.expectedsubmission')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_overrides_requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReminderPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('rules', models.JSONField(default=list, help_text='Approved offsets/channels/recipient roles')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_policies_approved', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_policies', to='submissions.reportingperiod')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_policies_prepared', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NonFilledDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('value', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='non_filled_disposition', to='submissions.submissionvalue')),
            ],
        ),
        migrations.CreateModel(
            name='DeadlineChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_due_at', models.DateTimeField()),
                ('proposed_due_at', models.DateTimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deadline_changes_decided', to=settings.AUTH_USER_MODEL)),
                ('expected_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_changes', to='submissions.expectedsubmission')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deadline_changes_requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CorrectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('SUBMISSION', 'Submission'), ('SECTION', 'Section'), ('FIELD', 'Field'), ('GRID_CELL', 'Grid Cell')], max_length=20)),
                ('target_id', models.CharField(max_length=100)),
                ('instruction', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ADDRESSED', 'Addressed'), ('VERIFIED', 'Verified')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('source_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_items', to='submissions.submission')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reminderpolicy',
            constraint=models.UniqueConstraint(fields=('period', 'version'), name='unique_period_reminder_version'),
        ),
    ]
