# Generated by Django 4.2.13 on 2026-08-12 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissions', '0002_validationrun_validationresult_submissionreceipt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=60)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('audience', models.CharField(choices=[('PROVIDER', 'Provider'), ('NCA', 'NCA'), ('BOTH', 'Both'), ('INTERNAL', 'Internal')], default='BOTH', max_length=10)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='correctionitem',
            name='resolution_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_correction_items', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='correctionitem',
            name='stage',
            field=models.CharField(choices=[('PROVIDER_APPROVAL', 'Provider Approval'), ('NCA_REVIEW', 'NCA Review')], default='NCA_REVIEW', max_length=25),
        ),
        migrations.AddField(
            model_name='submission',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='supersedes',
            field=models.OneToOneField(blank=True, help_text='Previous immutable official version cloned for correction.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='submissions.submission'),
        ),
        migrations.AlterField(
            model_name='expectedsubmission',
            name='workflow_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Provider Approval'), ('PROVIDER_CHANGES_REQUESTED', 'Provider Changes Requested'), ('PROVIDER_RESUBMITTED', 'Resubmitted to Provider Approver'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under NCA Review'), ('CORRECTION_REQUESTED', 'Correction Requested'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='NOT_STARTED', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='submissionvalue',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('field__isnull', False), ('grid__isnull', True), ('grid_column__isnull', True)), models.Q(('field__isnull', True), ('grid__isnull', False), ('grid_column__isnull', False)), _connector='OR'), name='submission_value_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='submissionvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('field__isnull', False)), fields=('submission', 'field'), name='unique_submission_scalar_value'),
        ),
        migrations.AddConstraint(
            model_name='submissionvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('grid__isnull', False)), fields=('submission', 'grid', 'grid_row_id', 'grid_column'), name='unique_submission_grid_cell'),
        ),
        migrations.AddField(
            model_name='submissionnotification',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='submissions.submissionevent'),
        ),
        migrations.AddField(
            model_name='submissionnotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissionnotification',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='submissionevent',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submission_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissionevent',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeline_events', to='submissions.submission'),
        ),
        migrations.AddConstraint(
            model_name='submissionnotification',
            constraint=models.UniqueConstraint(fields=('recipient', 'event'), name='unique_submission_event_recipient'),
        ),
    ]
