# Generated by Django 4.2.13 on 2026-08-12 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submissionevent_submissionnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectedsubmission',
            name='migration_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='expectedsubmission',
            name='replacement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaces_legacy_obligation', to='submissions.expectedsubmission'),
        ),
    ]
