# Generated by Django 5.2 on 2026-08-12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0004_expectedsubmission_migration_report_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="last_edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="last_edited_by",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_edited_submissions", to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ProviderEditBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stage", models.CharField(max_length=30)),
                ("section_code", models.CharField(max_length=100)),
                ("base_revision", models.PositiveIntegerField()),
                ("resulting_revision", models.PositiveIntegerField()),
                ("item_count", models.PositiveIntegerField(default=0)),
                ("changes_sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="provider_edit_batches", to=settings.AUTH_USER_MODEL)),
                ("submission", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="provider_edit_batches", to="submissions.submission")),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.CreateModel(
            name="ProviderEditItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_type", models.CharField(choices=[("FIELD", "Field"), ("GRID_CELL", "Grid cell")], max_length=20)),
                ("target_id", models.CharField(max_length=255)),
                ("before", models.JSONField(default=dict)),
                ("after", models.JSONField(default=dict)),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="items", to="submissions.providereditbatch")),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="ProviderApprovalDecision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attestation", models.BooleanField()),
                ("approval_note", models.TextField(blank=True)),
                ("change_summary", models.TextField(blank=True)),
                ("approver_edited", models.BooleanField(default=False)),
                ("edit_batch_count", models.PositiveIntegerField(default=0)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                ("approver", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="provider_approval_decisions", to=settings.AUTH_USER_MODEL)),
                ("submission", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="provider_approval", to="submissions.submission")),
            ],
        ),
    ]
