# Generated by Django 5.2.16 on 2026-08-18 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0016_formfield_source_row_formfield_source_sheet_and_more'),
        ('providers', '0003_providerformassignment'),
        ('submissions', '0007_section_save_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderWorkbookBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=500)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
                ('scan_status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEAN', 'Clean'), ('INFECTED', 'Infected'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('scan_engine', models.CharField(blank=True, max_length=100)),
                ('scan_details', models.TextField(blank=True)),
                ('main_sheet', models.CharField(default='REVISED MNOs MONTHLY DATA', max_length=255)),
                ('month_header_row', models.PositiveIntegerField(default=8)),
                ('first_month_column', models.PositiveIntegerField(default=6)),
                ('contact_cells', models.JSONField(blank=True, default=dict)),
                ('mapping_summary', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workbook_baselines_approved', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workbook_baselines', to='providers.providercontact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workbook_baselines_created', to=settings.AUTH_USER_MODEL)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_workbook_baselines', to='forms_engine.formtemplate')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workbook_baselines', to='providers.providerprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReportArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PREPARING', 'Preparing'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('SUPERSEDED', 'Superseded')], default='PREPARING', max_length=20)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('private_path', models.CharField(blank=True, max_length=500)),
                ('mime_type', models.CharField(default='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('submission_revision', models.PositiveIntegerField(default=0)),
                ('generation_metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_report_artifact', to='submissions.submission')),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='submissions.providerworkbookbaseline')),
            ],
        ),
        migrations.CreateModel(
            name='WorkbookIndicatorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_key', models.CharField(max_length=300)),
                ('target_type', models.CharField(choices=[('FIELD', 'Field'), ('GRID_CELL', 'Grid cell')], max_length=20)),
                ('sheet_name', models.CharField(max_length=255)),
                ('excel_row', models.PositiveIntegerField()),
                ('value_kind', models.CharField(choices=[('INPUT', 'Input'), ('CALCULATED', 'Calculated')], default='INPUT', max_length=20)),
                ('source_indicator', models.CharField(blank=True, max_length=500)),
                ('source_definition', models.TextField(blank=True)),
                ('source_data_type', models.CharField(blank=True, max_length=100)),
                ('formula_seed_column', models.PositiveIntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_mappings', to='submissions.providerworkbookbaseline')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workbook_mappings', to='forms_engine.formfield')),
                ('grid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workbook_mappings', to='forms_engine.formgrid')),
                ('grid_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workbook_mappings', to='forms_engine.gridcolumn')),
                ('grid_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workbook_mappings', to='forms_engine.gridrow')),
            ],
            options={
                'ordering': ['sheet_name', 'excel_row', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='providerworkbookbaseline',
            constraint=models.UniqueConstraint(fields=('provider', 'form_template', 'version'), name='unique_provider_form_workbook_baseline_version'),
        ),
        migrations.AddConstraint(
            model_name='providerworkbookbaseline',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('provider', 'form_template'), name='unique_active_provider_form_workbook_baseline'),
        ),
        migrations.AddConstraint(
            model_name='workbookindicatormapping',
            constraint=models.UniqueConstraint(fields=('baseline', 'target_key'), name='unique_baseline_indicator_target'),
        ),
        migrations.AddConstraint(
            model_name='workbookindicatormapping',
            constraint=models.UniqueConstraint(fields=('baseline', 'sheet_name', 'excel_row'), name='unique_baseline_sheet_indicator_row'),
        ),
    ]
