# Generated by Django 5.2.16 on 2026-09-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_expected_original_workflow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionvalue',
            name='source_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='submissionvalue',
            name='value_source',
            field=models.CharField(choices=[('MANUAL', 'Manual entry'), ('EXCEL_IMPORT', 'Excel import'), ('SYSTEM', 'System calculated')], default='MANUAL', max_length=20),
        ),
    ]
