# Generated by Django 5.0.6 on 2026-06-08 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('kmz_upload_required', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_code', models.CharField(choices=[('MNO-MONTHLY', 'MNO Monthly Return'), ('DC-TB02', 'Pay TV Broadcasting Annual'), ('DC-ISP06', 'Internet Service Provider Annual'), ('DC-ITC04', 'Infrastructure Tower Operator Annual'), ('TOWER-MAIN-ANNUAL', 'Infrastructure Tower Main Annual'), ('DC-DBS05', 'Domestic/Inland Fibre Semi-Annual'), ('DC-SUB03', 'International Submarine Fibre Annual')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('provider_category', models.CharField(max_length=30)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('SEMI_ANNUAL', 'Semi-Annual'), ('ANNUAL', 'Annual')], max_length=15)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('effective_from', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('kmz_required', models.BooleanField(default=False)),
                ('excel_backup_enabled', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['form_code'],
            },
        ),
        migrations.CreateModel(
            name='FormGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('row_mode', models.CharField(choices=[('FIXED', 'Fixed rows (e.g. Ghana regions)'), ('REPEATABLE', 'Repeatable rows (provider adds rows)')], max_length=15)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('instructions', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grids', to='forms_engine.formsection')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('section', 'grid_code')},
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_code', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('currency', 'Currency (GH₵)'), ('percentage', 'Percentage'), ('date', 'Date'), ('boolean', 'Boolean (Yes/No)'), ('select', 'Select'), ('multiselect', 'Multi-select'), ('textarea', 'Textarea'), ('coordinate', 'Coordinate'), ('formula', 'Formula (Calculated)'), ('declaration', 'Declaration / Checkbox')], max_length=20)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('help_text', models.TextField(blank=True)),
                ('formula', models.TextField(blank=True)),
                ('conditional_on_value', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('export_name', models.CharField(blank=True, max_length=100)),
                ('conditional_on_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditional_children', to='forms_engine.formfield')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms_engine.formsection')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('section', 'field_code')},
            },
        ),
        migrations.AddField(
            model_name='formsection',
            name='form_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='forms_engine.formtemplate'),
        ),
        migrations.CreateModel(
            name='GridRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_label', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_rows', to='forms_engine.formgrid')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='KMZUploadRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ROUTE', 'Route'), ('TOPOLOGY', 'Topology'), ('COVERAGE', 'Coverage'), ('NETWORK_MAP', 'Network Map')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('max_file_size_mb', models.PositiveIntegerField(default=50)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kmz_requirements', to='forms_engine.formtemplate')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_engine.formsection')),
            ],
        ),
        migrations.CreateModel(
            name='SelectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='forms_engine.formfield')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='formsection',
            unique_together={('form_template', 'section_code')},
        ),
        migrations.CreateModel(
            name='GridColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_code', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('currency', 'Currency (GH₵)'), ('percentage', 'Percentage'), ('date', 'Date'), ('boolean', 'Boolean (Yes/No)'), ('select', 'Select'), ('multiselect', 'Multi-select'), ('textarea', 'Textarea'), ('coordinate', 'Coordinate'), ('formula', 'Formula (Calculated)'), ('declaration', 'Declaration / Checkbox')], max_length=20)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='forms_engine.formgrid')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('grid', 'column_code')},
            },
        ),
    ]
