# Generated by Django 5.0.6 on 2026-06-08 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridrow',
            name='grid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_rows', to='forms_engine.formgrid'),
        ),
    ]
