# Generated by Django 4.2.13 on 2026-08-05 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_form_families(apps, schema_editor):
    FormFamily = apps.get_model('forms_engine', 'FormFamily')
    FormTemplate = apps.get_model('forms_engine', 'FormTemplate')
    for template in FormTemplate.objects.all():
        pending = template.form_code == 'DC-DBS05'
        family, _ = FormFamily.objects.get_or_create(
            code=template.form_code,
            defaults={
                'name': template.name,
                'canonical_frequency': '' if pending else template.frequency,
                'frequency_decision_status': 'PENDING_DECISION' if pending else 'APPROVED',
            },
        )
        template.family_id = family.id
        # Preserve demo usability, while the legacy marker remains a production readiness blocker.
        template.mapping_complete = True
        template.approval_status = 'APPROVED'
        template.source_reference = 'LEGACY-DEMO-NOT-FOR-PRODUCTION'
        template.save(update_fields=['family', 'mapping_complete', 'approval_status', 'source_reference'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms_engine', '0003_formtemplate_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('MNO-MONTHLY', 'MNO Monthly Return'), ('DC-TB02', 'Pay TV Broadcasting Annual'), ('DC-ISP06', 'Internet Service Provider Annual'), ('DC-ITC04', 'Infrastructure Tower Operator Annual'), ('TOWER-MAIN-ANNUAL', 'Infrastructure Tower Main Annual'), ('DC-DBS05', 'Domestic/Inland Fibre Semi-Annual'), ('DC-SUB03', 'International Submarine Fibre Annual')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('canonical_frequency', models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('SEMI_ANNUAL', 'Semi-Annual'), ('ANNUAL', 'Annual')], max_length=15)),
                ('frequency_decision_status', models.CharField(choices=[('PENDING_DECISION', 'Pending source-owner decision'), ('APPROVED', 'Approved')], default='APPROVED', max_length=25)),
                ('frequency_decision_reference', models.CharField(blank=True, max_length=255)),
                ('source_owner', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('TYPE', 'Data type'), ('RANGE', 'Range'), ('OPTION', 'Allowed option'), ('DATE', 'Date'), ('COORDINATE', 'Coordinate'), ('CONDITIONAL', 'Conditional'), ('FORMULA', 'Formula'), ('COMPARISON', 'Cross-field comparison'), ('GRID_TOTAL', 'Grid total')], max_length=20)),
                ('severity', models.CharField(choices=[('BLOCK', 'Blocking'), ('WARN', 'Warning')], default='BLOCK', max_length=10)),
                ('parameters', models.JSONField(default=dict)),
                ('message', models.CharField(max_length=500)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_versions_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='mapping_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_versions_prepared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='source_reference',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='source_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='form_code',
            field=models.CharField(choices=[('MNO-MONTHLY', 'MNO Monthly Return'), ('DC-TB02', 'Pay TV Broadcasting Annual'), ('DC-ISP06', 'Internet Service Provider Annual'), ('DC-ITC04', 'Infrastructure Tower Operator Annual'), ('TOWER-MAIN-ANNUAL', 'Infrastructure Tower Main Annual'), ('DC-DBS05', 'Domestic/Inland Fibre Semi-Annual'), ('DC-SUB03', 'International Submarine Fibre Annual')], max_length=20),
        ),
        migrations.AddField(
            model_name='validationrule',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_rules', to='forms_engine.formfield'),
        ),
        migrations.AddField(
            model_name='validationrule',
            name='form_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_rules', to='forms_engine.formtemplate'),
        ),
        migrations.AddField(
            model_name='validationrule',
            name='grid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_rules', to='forms_engine.formgrid'),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='forms_engine.formfamily'),
        ),
        migrations.RunPython(migrate_form_families, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='formtemplate',
            constraint=models.UniqueConstraint(fields=('family', 'version'), name='unique_form_family_version'),
        ),
    ]
