# Generated by Django 4.2.13 on 2026-08-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0007_form_specific_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfamily',
            name='code_status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PROVISIONAL', 'Provisional')], default='CONFIRMED', max_length=15),
        ),
    ]
