# Generated by Django 5.2.16 on 2026-08-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0015_matrix_grid_workbook_parser'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='source_row',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='source_sheet',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='formgrid',
            name='source_row',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formgrid',
            name='source_sheet',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gridcolumn',
            name='source_row',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gridcolumn',
            name='source_sheet',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gridrow',
            name='source_rows',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gridrow',
            name='source_sheet',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
