# Generated by Django 5.2.16 on 2026-08-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0022_data_entry_table_parser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('currency', 'Currency (GH₵)'), ('percentage', 'Percentage'), ('date', 'Date'), ('boolean', 'Boolean (Yes/No)'), ('select', 'Select'), ('multiselect', 'Multi-select'), ('textarea', 'Textarea'), ('coordinate', 'Coordinate'), ('formula', 'Formula (Calculated)'), ('declaration', 'Declaration / Checkbox'), ('attachment', 'Document attachment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gridcolumn',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('currency', 'Currency (GH₵)'), ('percentage', 'Percentage'), ('date', 'Date'), ('boolean', 'Boolean (Yes/No)'), ('select', 'Select'), ('multiselect', 'Multi-select'), ('textarea', 'Textarea'), ('coordinate', 'Coordinate'), ('formula', 'Formula (Calculated)'), ('declaration', 'Declaration / Checkbox'), ('attachment', 'Document attachment')], max_length=20),
        ),
    ]
