import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_templates(apps, schema_editor):
    Template = apps.get_model("reports", "ReportTemplate")
    common = [
        {"key": "mobile_voice_subscriptions", "section": "Mobile Network Services", "location": "Subscriptions table and figures", "label": "Mobile Voice Subscriptions", "form_code": "MNO-MONTHLY", "field_code": "TOTAL_MOBILE_CELLULAR_VOICE_SUBSCRIPTIONS_PREPAID_POSTPAID", "provider_category": "MNO", "period_aggregation": "PERIOD_END", "provider_aggregation": "SUM", "window": "CURRENT", "decimal_places": 0, "required": True},
        {"key": "mobile_data_subscriptions", "section": "Mobile Network Services", "location": "Data subscriptions table and figures", "label": "Mobile Data Subscriptions", "form_code": "MNO-MONTHLY", "field_code": "TOTAL_MOBILE_CELLULAR_DATA_SUBSCRIPTIONS", "provider_category": "MNO", "period_aggregation": "PERIOD_END", "provider_aggregation": "SUM", "window": "CURRENT", "decimal_places": 0, "required": True},
        {"key": "mobile_data_traffic", "section": "Mobile Network Services", "location": "Data traffic table and figures", "label": "Mobile Data Traffic", "form_code": "MNO-MONTHLY", "field_code": "TOTAL_MOBILE_DATA_INTERNET_VOLUMES", "provider_category": "MNO", "period_aggregation": "SUM", "provider_aggregation": "SUM", "window": "CURRENT", "decimal_places": 2, "required": True},
        {"key": "fixed_broadband_subscriptions", "section": "Fixed Network Services", "location": "Fixed broadband table and figures", "label": "Fixed Broadband Subscriptions", "form_code": "MNO-MONTHLY", "field_code": "TOTAL_FIXED_BROADBAND_SUBSCRIPTIONS", "provider_category": "MNO", "period_aggregation": "PERIOD_END", "provider_aggregation": "SUM", "window": "CURRENT", "decimal_places": 0, "required": True},
    ]
    Template.objects.create(report_type="QUARTERLY_BULLETIN", name="Quarterly Statistical Bulletin on Communications in Ghana", version=1, effective_year=2025, effective_quarter=4,
        filename_pattern="Q{quarter}-{year}-Statistical-Bulletin.pdf", source_reference="Q4-2025-Statistical-Bulletin.pdf", source_sha256="7a7aeefc4d9cddfffdc81ac6f9c5ba6074c411c30355e58278b2df5a15ee5cd5",
        immutable_blocks=["QUARTERLY STATISTICAL BULLETIN ON COMMUNICATIONS IN GHANA", "Author: National Communications Authority (NCA)"],
        field_mappings=common, calculation_mappings=[{"key": "direction", "method": "SIGN", "positive": "increased", "negative": "decreased", "zero": "remained unchanged"}],
        layout_definition={"reference_pages": 54, "page_size": "A4"}, status="ARCHIVED")
    Template.objects.create(report_type="QUARTERLY_BULLETIN", name="Quarterly Statistical Bulletin on Communications in Ghana", version=2, effective_year=2026, effective_quarter=1,
        filename_pattern="Q{quarter}_{year}_Statistical_Bulletin.pdf", source_reference="Q1_2026_Statistical_Bulletin.pdf", source_sha256="d283e21ada39180b6395e62aff0b2f12392b2347860903acd8f09ac9bffeb959",
        immutable_blocks=["QUARTERLY STATISTICAL BULLETIN ON COMMUNICATIONS IN GHANA", "Author: National Communications Authority (NCA)", "The Bulletin is available at www.nca.org.gh"],
        field_mappings=common + [{"key": "unmapped_broadcasting", "section": "Broadcasting", "location": "Authorised stations tables", "label": "Authorised and operational FM and television stations", "required": True}],
        calculation_mappings=[{"key": "direction", "method": "SIGN", "positive": "increased", "negative": "decreased", "zero": "remained unchanged"}],
        layout_definition={"reference_pages": 55, "page_size": "A4", "reference_comparison": "Q4-2025-Statistical-Bulletin.pdf"}, status="ACTIVE")
    Template.objects.create(report_type="CIR", name="Communications Industry Report (CIR)", version=1, effective_year=2024,
        filename_pattern="{year}-COMMUNICATONS-INDUSTRY-REPORTS.pdf", source_reference="2024-COMMUNICATONS-INDUSTRY-REPORTS.pdf", source_sha256="83895415249eed25cb7384df0d9022b3e92e72dfe8a6019da5e71313dc79ec97",
        immutable_blocks=["COMMUNICATIONS INDUSTRY REPORT (CIR)", "NATIONAL COMMUNICATIONS AUTHORITY"], field_mappings=common,
        calculation_mappings=[{"key": "cagr", "method": "CAGR", "window": "HISTORICAL_5Y"}], layout_definition={"reference_pages": 87, "page_size": "A4"}, status="ARCHIVED")
    Template.objects.create(report_type="CIR", name="Communications Industry Report (CIR)", version=2, effective_year=2025,
        filename_pattern="{year}-CIR.pdf", source_reference="2025-CIR.pdf", source_sha256="90879469cf6a0ef27f6c61294e88aaf4c2db15c5839347e932288106ec3aa8ae",
        immutable_blocks=["COMMUNICATIONS INDUSTRY REPORT (CIR)", "NATIONAL COMMUNICATIONS AUTHORITY", "NCA CONTACTS AND PRESENCE COUNTRYWIDE"],
        field_mappings=common + [{"key": "unmapped_licensing", "section": "Industry Overview", "location": "Authorisation and licence tables", "label": "Industry authorisations, licences and economic indicators", "required": True}],
        calculation_mappings=[{"key": "cagr", "method": "CAGR", "window": "HISTORICAL_5Y"}, {"key": "direction", "method": "SIGN", "positive": "increased", "negative": "decreased", "zero": "remained unchanged"}],
        layout_definition={"reference_pages": 97, "page_size": "A4", "reference_comparison": "2024-COMMUNICATONS-INDUSTRY-REPORTS.pdf"}, status="ACTIVE")


class Migration(migrations.Migration):
    initial = True
    dependencies = [("users", "0005_user_must_change_password"), ("submissions", "0015_expectedsubmission_penalty")]
    operations = [
        migrations.CreateModel(name="ReportTemplate", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("report_type", models.CharField(choices=[("QUARTERLY_BULLETIN", "Quarterly Statistical Bulletin"), ("CIR", "Communications Industry Report")], db_index=True, max_length=30)), ("name", models.CharField(max_length=255)), ("version", models.PositiveIntegerField()), ("effective_year", models.PositiveIntegerField()), ("effective_quarter", models.PositiveSmallIntegerField(blank=True, null=True)), ("filename_pattern", models.CharField(max_length=255)), ("source_reference", models.CharField(max_length=255)), ("source_sha256", models.CharField(max_length=64)), ("immutable_blocks", models.JSONField(default=list)), ("field_mappings", models.JSONField(default=list)), ("calculation_mappings", models.JSONField(default=list)), ("layout_definition", models.JSONField(default=dict)), ("status", models.CharField(choices=[("DRAFT", "Draft"), ("ACTIVE", "Active"), ("ARCHIVED", "Archived")], default="DRAFT", max_length=20)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name="report_templates_created", to=settings.AUTH_USER_MODEL))], options={"ordering": ["report_type", "-version"]}),
        migrations.CreateModel(name="ReportPublicationMetadata", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("report_type", models.CharField(choices=[("QUARTERLY_BULLETIN", "Quarterly Statistical Bulletin"), ("CIR", "Communications Industry Report")], max_length=30)), ("year", models.PositiveIntegerField()), ("quarter", models.PositiveSmallIntegerField(blank=True, null=True)), ("volume", models.PositiveIntegerField(blank=True, null=True)), ("issue", models.PositiveIntegerField(blank=True, null=True)), ("metadata", models.JSONField(blank=True, default=dict)), ("updated_at", models.DateTimeField(auto_now=True)), ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="ReportPreparation", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("report_type", models.CharField(choices=[("QUARTERLY_BULLETIN", "Quarterly Statistical Bulletin"), ("CIR", "Communications Industry Report")], max_length=30)), ("year", models.PositiveIntegerField()), ("quarter", models.PositiveSmallIntegerField(blank=True, null=True)), ("status", models.CharField(choices=[("READY", "Ready"), ("MISSING_DATA", "Missing Data"), ("MAPPING_REQUIRED", "Mapping Required"), ("CALCULATION_ERROR", "Calculation Error"), ("STALE", "Stale")], max_length=30)), ("manifest", models.JSONField(default=dict)), ("source_fingerprint", models.CharField(max_length=64)), ("created_at", models.DateTimeField(auto_now_add=True)), ("expires_at", models.DateTimeField()), ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="report_preparations", to=settings.AUTH_USER_MODEL)), ("template", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="preparations", to="reports.reporttemplate"))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="GeneratedReport", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("status", models.CharField(choices=[("PREPARING", "Preparing"), ("READY", "Ready"), ("FAILED", "Failed")], default="PREPARING", max_length=20)), ("filename", models.CharField(blank=True, max_length=255)), ("private_path", models.CharField(blank=True, max_length=500)), ("mime_type", models.CharField(default="application/pdf", max_length=100)), ("file_size", models.PositiveBigIntegerField(default=0)), ("sha256", models.CharField(blank=True, max_length=64)), ("source_fingerprint", models.CharField(max_length=64)), ("validation_result", models.JSONField(default=dict)), ("error_message", models.TextField(blank=True)), ("idempotency_key", models.UUIDField(unique=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("completed_at", models.DateTimeField(blank=True, null=True)), ("generated_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="generated_reports", to=settings.AUTH_USER_MODEL)), ("preparation", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="generated_reports", to="reports.reportpreparation"))], options={"ordering": ["-created_at"]}),
        migrations.AddConstraint(model_name="reporttemplate", constraint=models.UniqueConstraint(fields=("report_type", "version"), name="unique_report_template_version")),
        migrations.AddConstraint(model_name="reporttemplate", constraint=models.UniqueConstraint(condition=models.Q(("status", "ACTIVE")), fields=("report_type",), name="unique_active_report_template")),
        migrations.AddConstraint(model_name="reportpublicationmetadata", constraint=models.UniqueConstraint(fields=("report_type", "year", "quarter"), name="unique_report_publication_period")),
        migrations.RunPython(seed_templates, migrations.RunPython.noop),
    ]
