# Generated by Django 4.2.13 on 2026-08-03 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requester_name', models.CharField(max_length=255)),
                ('requester_email', models.EmailField(max_length=254)),
                ('requesting_division', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('requested_format', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'XLSX'), ('PDF', 'PDF')], max_length=5)),
                ('scope', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('CHANGES_REQUESTED', 'Changes Requested'), ('APPROVED', 'Approved'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('GENERATION_FAILED', 'Generation Failed'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('EXPIRED', 'Expired')], db_index=True, default='SUBMITTED', max_length=30)),
                ('expected_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('approval_manifest', models.JSONField(blank=True, null=True)),
                ('projected_row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_data_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRequestNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_request_notifications', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='data_requests.datarequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('event_type', models.CharField(max_length=50)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='data_requests.datarequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRequestArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_path', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=150)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artifact', to='data_requests.datarequest')),
            ],
        ),
    ]
