# Generated by Django 5.0.6 on 2026-06-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('recipients', models.JSONField(help_text='[{"email": "...", "name": "..."}]')),
                ('cc', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('compliance_stage', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='DRAFT', max_length=10)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('PERIOD_OPEN', 'Period Opening Notice'), ('REMINDER', 'Submission Reminder'), ('DRAFT_INCOMPLETE', 'Draft Incomplete Reminder'), ('MISSING_FIELDS', 'Missing Required Fields'), ('CORRECTION_REQUEST', 'Correction Request'), ('OVERDUE', 'Overdue Notice'), ('ESCALATION', 'Escalation Notice'), ('PENALTY_WARNING', 'Penalty Warning'), ('FINAL_NOTICE', 'Final Compliance Notice')], max_length=30, unique=True)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('placeholders', models.JSONField(default=list, help_text='List of placeholder variable names')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
