# Generated by Django 5.0.6 on 2026-06-15 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
        ("providers", "0001_initial"),
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceFlag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("flag_type", models.CharField(choices=[("MISSING_DATA", "Missing Required Data"), ("OVERDUE", "Overdue Submission"), ("INCOMPLETE", "Incomplete Form"), ("CORRECTION", "Correction Requested")], max_length=20)),
                ("description", models.TextField(help_text="What is missing or needs attention")),
                ("missing_field_count", models.PositiveIntegerField(default=0)),
                ("completion_percentage", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(choices=[("OPEN", "Open"), ("ACKNOWLEDGED", "Acknowledged by Provider"), ("IN_PROGRESS", "In Progress"), ("RESOLVED", "Resolved")], default="OPEN", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("expected_submission", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="compliance_flags", to="submissions.expectedsubmission")),
                ("provider", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="compliance_flags", to="providers.providerprofile")),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("expected_submission", "flag_type")},
            },
        ),
    ]
