# Generated by Django 5.0.6 on 2026-06-17 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_complianceflag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['template_type']},
        ),
    ]
