# Generated by Django 4.2.13 on 2026-06-17 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0003_alter_emailtemplate_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagCorrespondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('NOTE', 'Internal Note'), ('EMAIL_SENT', 'Email Sent to Provider'), ('EMAIL_RECEIVED', 'Email from Provider')], default='NOTE', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='For emails', max_length=500)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('email_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondence', to='compliance.emaillog')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondence', to='compliance.complianceflag')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
