# Generated by Django 4.2.13 on 2026-08-05 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def approve_legacy_templates(apps, schema_editor):
    EmailTemplate = apps.get_model("compliance", "EmailTemplate")
    EmailTemplate.objects.all().update(status="APPROVED", version=1)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0004_flagcorrespondence'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=30)),
                ('provider_event_id', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionalOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('aggregate_type', models.CharField(max_length=100)),
                ('aggregate_id', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='emaillog',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='provider_key',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('BOUNCED', 'Bounced'), ('FAILED', 'Failed')], default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('PERIOD_OPEN', 'Period Opening Notice'), ('REMINDER', 'Submission Reminder'), ('DRAFT_INCOMPLETE', 'Draft Incomplete Reminder'), ('MISSING_FIELDS', 'Missing Required Fields'), ('CORRECTION_REQUEST', 'Correction Request'), ('OVERDUE', 'Overdue Notice'), ('ESCALATION', 'Escalation Notice'), ('PENALTY_WARNING', 'Penalty Warning'), ('FINAL_NOTICE', 'Final Compliance Notice')], max_length=30),
        ),
        migrations.RunPython(approve_legacy_templates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='emailtemplate',
            constraint=models.UniqueConstraint(fields=('template_type', 'version'), name='unique_email_template_version'),
        ),
        migrations.AddField(
            model_name='emaildeliveryevent',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_events', to='compliance.emaillog'),
        ),
    ]
