# Generated by Django 5.2.16 on 2026-09-01 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_emaildeliveryevent_transactionaloutbox_and_more'),
        ('submissions', '0011_expected_original_workflow_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphMailboxState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox', models.EmailField(max_length=254, unique=True)),
                ('subscription_id', models.CharField(blank=True, max_length=255)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('delta_link', models.TextField(blank=True)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='emaillog',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='sender_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('RETRYING', 'Retrying'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('BOUNCED', 'Bounced'), ('FAILED', 'Failed')], default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('PERIOD_OPEN', 'Period Opening Notice'), ('FORM_ASSIGNED', 'New Form Assigned'), ('REMINDER', 'Submission Reminder'), ('DEADLINE_REMINDER', 'Deadline Reminder'), ('DRAFT_INCOMPLETE', 'Draft Incomplete Reminder'), ('MISSING_FIELDS', 'Missing Required Fields'), ('SUBMITTED_FOR_APPROVAL', 'Form Submitted for Approval'), ('CORRECTION_REQUEST', 'Correction Request'), ('PROVIDER_RESUBMITTED', 'Provider Resubmission'), ('SUBMITTED_TO_NCA', 'Submission Sent to NCA'), ('NCA_ACKNOWLEDGEMENT', 'NCA Receipt Acknowledgement'), ('NCA_CORRECTION_REQUEST', 'NCA Correction Request'), ('SUBMISSION_REJECTED', 'Submission Rejected'), ('SUBMISSION_APPROVED', 'Submission Approved'), ('DEADLINE_CHANGED', 'Deadline Changed'), ('COMPLIANCE_NOTICE', 'Compliance Notice'), ('SUBMISSION_CORRESPONDENCE', 'General Submission Correspondence'), ('OVERDUE', 'Overdue Notice'), ('ESCALATION', 'Escalation Notice'), ('PENALTY_WARNING', 'Penalty Warning'), ('FINAL_NOTICE', 'Final Compliance Notice')], max_length=30),
        ),
        migrations.CreateModel(
            name='CommunicationPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('action_payload', models.JSONField(default=dict)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('recipients', models.JSONField(default=list)),
                ('cc', models.JSONField(default=list)),
                ('attachments', models.JSONField(default=list)),
                ('submission_revision', models.PositiveIntegerField(blank=True, null=True)),
                ('workflow_status', models.CharField(blank=True, max_length=30)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_previews', to=settings.AUTH_USER_MODEL)),
                ('compliance_flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_previews', to='compliance.complianceflag')),
                ('expected_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_previews', to='submissions.expectedsubmission')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_previews', to='submissions.submission')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compliance.emailtemplate')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('channel', models.CharField(choices=[('SYSTEM', 'System Notification'), ('EMAIL', 'Email'), ('BOTH', 'System and Email')], max_length=10)),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Outbound'), ('INBOUND', 'Inbound'), ('INTERNAL', 'Internal')], default='OUTBOUND', max_length=10)),
                ('sender_snapshot', models.JSONField(default=dict)),
                ('recipients', models.JSONField(default=list)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField()),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(blank=True, max_length=30)),
                ('submission_reference', models.CharField(blank=True, db_index=True, max_length=180)),
                ('attachments', models.JSONField(default=list)),
                ('content_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compliance_flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='compliance.complianceflag')),
                ('email_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communication', to='compliance.emaillog')),
                ('expected_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communications', to='submissions.expectedsubmission')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communications_sent', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communications', to='submissions.submission')),
                ('submission_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communications', to='submissions.submissionevent')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IncomingMailboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_message_id', models.CharField(max_length=255, unique=True)),
                ('internet_message_id', models.CharField(blank=True, max_length=500)),
                ('conversation_id', models.CharField(blank=True, max_length=255)),
                ('sender', models.JSONField(default=dict)),
                ('recipients', models.JSONField(default=list)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True)),
                ('received_at', models.DateTimeField()),
                ('reference', models.CharField(blank=True, db_index=True, max_length=180)),
                ('link_status', models.CharField(choices=[('MATCHED', 'Matched'), ('UNMATCHED', 'Unmatched'), ('LINKED', 'Manually linked')], default='UNMATCHED', max_length=20)),
                ('attachments', models.JSONField(default=list)),
                ('raw_metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('communication', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_message', to='compliance.communicationrecord')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_mail', to='submissions.submission')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
            },
        ),
    ]
