# Generated by Django 5.2.16 on 2026-09-01 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0007_workflow_email_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingEmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_attachment_id', models.CharField(blank=True, max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=150)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('storage_path', models.CharField(max_length=500)),
                ('sha256', models.CharField(max_length=64)),
                ('scan_status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEAN', 'Clean'), ('INFECTED', 'Infected'), ('ERROR', 'Error')], default='PENDING', max_length=12)),
                ('scan_engine', models.CharField(blank=True, max_length=100)),
                ('scan_details', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantined_attachments', to='compliance.incomingmailboxmessage')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('message', 'provider_attachment_id'), name='unique_incoming_message_attachment')],
            },
        ),
    ]
