# Generated by Django 5.2.16 on 2026-09-01 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0009_externalemailhandoff'),
        ('submissions', '0012_submissionvalue_source_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='communicationrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('submission_event__isnull', False)), fields=('submission_event',), name='unique_communication_per_submission_event'),
        ),
    ]
